// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_opensearch_catalog

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func OpensearchCatalogDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"access_key": schema.StringAttribute{
				Computed:            true,
				Description:         "AWS access key",
				MarkdownDescription: "AWS access key",
			},
			"auth_type": schema.StringAttribute{
				Computed: true,
			},
			"catalog_id": schema.StringAttribute{
				Required:            true,
				Description:         "A catalog connecting to OpenSearch",
				MarkdownDescription: "A catalog connecting to OpenSearch",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "Catalog description",
				MarkdownDescription: "Catalog description",
			},
			"endpoint": schema.StringAttribute{
				Computed:            true,
				Description:         "OpenSearch cluster endpoint",
				MarkdownDescription: "OpenSearch cluster endpoint",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Catalog name",
				MarkdownDescription: "Catalog name",
			},
			"password": schema.StringAttribute{
				Computed:            true,
				Description:         "Password",
				MarkdownDescription: "Password",
			},
			"port": schema.Int64Attribute{
				Computed:            true,
				Description:         "OpenSearch cluster port. Defaults to 443.",
				MarkdownDescription: "OpenSearch cluster port. Defaults to 443.",
			},
			"read_only": schema.BoolAttribute{
				Computed:            true,
				Description:         "Is catalog read only",
				MarkdownDescription: "Is catalog read only",
			},
			"region": schema.StringAttribute{
				Computed:            true,
				Description:         "AWS region",
				MarkdownDescription: "AWS region",
			},
			"role_arn": schema.StringAttribute{
				Computed:            true,
				Description:         "AWS cross account role ARN",
				MarkdownDescription: "AWS cross account role ARN",
			},
			"secret_key": schema.StringAttribute{
				Computed:            true,
				Description:         "AWS secret key",
				MarkdownDescription: "AWS secret key",
			},
			"ssh_tunnel_id": schema.StringAttribute{
				Computed:            true,
				Description:         "SSH tunnel identifier",
				MarkdownDescription: "SSH tunnel identifier",
			},
			"username": schema.StringAttribute{
				Computed:            true,
				Description:         "Username",
				MarkdownDescription: "Username",
			},
			"validate": schema.BoolAttribute{
				Computed:            true,
				Description:         "Validate catalog configuration before creation",
				MarkdownDescription: "Validate catalog configuration before creation",
			},
		},
	}
}

type OpensearchCatalogModel struct {
	AccessKey   types.String `tfsdk:"access_key"`
	AuthType    types.String `tfsdk:"auth_type"`
	CatalogId   types.String `tfsdk:"catalog_id"`
	Description types.String `tfsdk:"description"`
	Endpoint    types.String `tfsdk:"endpoint"`
	Name        types.String `tfsdk:"name"`
	Password    types.String `tfsdk:"password"`
	Port        types.Int64  `tfsdk:"port"`
	ReadOnly    types.Bool   `tfsdk:"read_only"`
	Region      types.String `tfsdk:"region"`
	RoleArn     types.String `tfsdk:"role_arn"`
	SecretKey   types.String `tfsdk:"secret_key"`
	SshTunnelId types.String `tfsdk:"ssh_tunnel_id"`
	Username    types.String `tfsdk:"username"`
	Validate    types.Bool   `tfsdk:"validate"`
}
