// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_mysql_catalog

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func MysqlCatalogDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"catalog_id": schema.StringAttribute{
				Required:            true,
				Description:         "A catalog connecting to MySQL",
				MarkdownDescription: "A catalog connecting to MySQL",
			},
			"cloud_kind": schema.StringAttribute{
				Computed:            true,
				Description:         "MySQL cloud kind. Defaults to AWS.",
				MarkdownDescription: "MySQL cloud kind. Defaults to AWS.",
			},
			"connection_type": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "Catalog description",
				MarkdownDescription: "Catalog description",
			},
			"host": schema.StringAttribute{
				Computed:            true,
				Description:         "MySQL host",
				MarkdownDescription: "MySQL host",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Catalog name",
				MarkdownDescription: "Catalog name",
			},
			"password": schema.StringAttribute{
				Computed:            true,
				Description:         "MySQL database password",
				MarkdownDescription: "MySQL database password",
			},
			"port": schema.Int64Attribute{
				Computed:            true,
				Description:         "MySQL database port. Defaults to 3306.",
				MarkdownDescription: "MySQL database port. Defaults to 3306.",
			},
			"private_link_id": schema.StringAttribute{
				Computed:            true,
				Description:         "PrivateLink Identifier",
				MarkdownDescription: "PrivateLink Identifier",
			},
			"read_only": schema.BoolAttribute{
				Computed:            true,
				Description:         "Is catalog read only",
				MarkdownDescription: "Is catalog read only",
			},
			"ssh_tunnel_id": schema.StringAttribute{
				Computed:            true,
				Description:         "SSH tunnel identifier",
				MarkdownDescription: "SSH tunnel identifier",
			},
			"username": schema.StringAttribute{
				Computed:            true,
				Description:         "MySQL database username",
				MarkdownDescription: "MySQL database username",
			},
			"validate": schema.BoolAttribute{
				Computed:            true,
				Description:         "Validate catalog configuration before creation",
				MarkdownDescription: "Validate catalog configuration before creation",
			},
		},
	}
}

type MysqlCatalogModel struct {
	CatalogId      types.String `tfsdk:"catalog_id"`
	CloudKind      types.String `tfsdk:"cloud_kind"`
	ConnectionType types.String `tfsdk:"connection_type"`
	Description    types.String `tfsdk:"description"`
	Host           types.String `tfsdk:"host"`
	Name           types.String `tfsdk:"name"`
	Password       types.String `tfsdk:"password"`
	Port           types.Int64  `tfsdk:"port"`
	PrivateLinkId  types.String `tfsdk:"private_link_id"`
	ReadOnly       types.Bool   `tfsdk:"read_only"`
	SshTunnelId    types.String `tfsdk:"ssh_tunnel_id"`
	Username       types.String `tfsdk:"username"`
	Validate       types.Bool   `tfsdk:"validate"`
}
