// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_row_filter

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func RowFilterDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created": schema.StringAttribute{
				Computed:            true,
				Description:         "Created on (read only)",
				MarkdownDescription: "Created on (read only)",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "Description (read only)",
				MarkdownDescription: "Description (read only)",
			},
			"expression": schema.StringAttribute{
				Computed:            true,
				Description:         "Row Filter expression (read only)",
				MarkdownDescription: "Row Filter expression (read only)",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "- A row filter\n- This parameter can be looked up using `name` instead of its Id. Use `name=value` instead of an Id to lookup/search using the `value`. `value` must be encoded ([see RFC](https://www.rfc-editor.org/rfc/rfc3986#section-2.2) including `=`)\n",
				MarkdownDescription: "- A row filter\n- This parameter can be looked up using `name` instead of its Id. Use `name=value` instead of an Id to lookup/search using the `value`. `value` must be encoded ([see RFC](https://www.rfc-editor.org/rfc/rfc3986#section-2.2) including `=`)\n",
			},
			"modified": schema.StringAttribute{
				Computed:            true,
				Description:         "Modified on (read only)",
				MarkdownDescription: "Modified on (read only)",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Row Filter name (read only)",
				MarkdownDescription: "Row Filter name (read only)",
			},
			"row_filter_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Row Filter ID (read only)",
				MarkdownDescription: "Row Filter ID (read only)",
			},
		},
	}
}

type RowFilterModel struct {
	Created     types.String `tfsdk:"created"`
	Description types.String `tfsdk:"description"`
	Expression  types.String `tfsdk:"expression"`
	Id          types.String `tfsdk:"id"`
	Modified    types.String `tfsdk:"modified"`
	Name        types.String `tfsdk:"name"`
	RowFilterId types.String `tfsdk:"row_filter_id"`
}
