// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_sql_job_status

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SqlJobStatusDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"error_message": schema.StringAttribute{
				Computed:            true,
				Description:         "Error encountered when SQL query was run (read only)",
				MarkdownDescription: "Error encountered when SQL query was run (read only)",
			},
			"progress_percentage": schema.Float64Attribute{
				Computed:            true,
				Description:         "Percentage progress of SQL job execution (read only)",
				MarkdownDescription: "Percentage progress of SQL job execution (read only)",
			},
			"query_id": schema.StringAttribute{
				Computed:            true,
				Description:         "ID of SQL query (read only)",
				MarkdownDescription: "ID of SQL query (read only)",
			},
			"sql_job_id": schema.StringAttribute{
				Required:            true,
				Description:         "SQL query scheduled job",
				MarkdownDescription: "SQL query scheduled job",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "SQL job status (read only)",
				MarkdownDescription: "SQL job status (read only)",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "Status last update time (read only)",
				MarkdownDescription: "Status last update time (read only)",
			},
		},
	}
}

type SqlJobStatusModel struct {
	ErrorMessage       types.String  `tfsdk:"error_message"`
	ProgressPercentage types.Float64 `tfsdk:"progress_percentage"`
	QueryId            types.String  `tfsdk:"query_id"`
	SqlJobId           types.String  `tfsdk:"sql_job_id"`
	Status             types.String  `tfsdk:"status"`
	UpdatedAt          types.String  `tfsdk:"updated_at"`
}
