// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_cluster

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ClusterResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"batch_cluster": schema.BoolAttribute{
				Computed:            true,
				Description:         "Supports resource intensive query processing mode (read only)",
				MarkdownDescription: "Supports resource intensive query processing mode (read only)",
			},
			"catalog_refs": schema.ListAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "Catalog IDs to attach to the cluster",
				MarkdownDescription: "Catalog IDs to attach to the cluster",
			},
			"cloud_region_id": schema.StringAttribute{
				Required:            true,
				Description:         "Cloud region ID of where the cluster will be created",
				MarkdownDescription: "Cloud region ID of where the cluster will be created",
			},
			"cluster_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Cluster ID (read only)",
				MarkdownDescription: "Cluster ID (read only)",
			},
			"cluster_state": schema.StringAttribute{
				Computed:            true,
				Description:         "Cluster state (read only)",
				MarkdownDescription: "Cluster state (read only)",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "- A Trino cluster\n- This parameter can be looked up using `name` instead of its Id. Use `name=value` instead of an Id to lookup/search using the `value`. `value` must be encoded ([see RFC](https://www.rfc-editor.org/rfc/rfc3986#section-2.2) including `=`)\n",
				MarkdownDescription: "- A Trino cluster\n- This parameter can be looked up using `name` instead of its Id. Use `name=value` instead of an Id to lookup/search using the `value`. `value` must be encoded ([see RFC](https://www.rfc-editor.org/rfc/rfc3986#section-2.2) including `=`)\n",
			},
			"idle_stop_minutes": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Idle suspend duration (in minutes)",
				MarkdownDescription: "Idle suspend duration (in minutes)",
			},
			"max_workers": schema.Int64Attribute{
				Required:            true,
				Description:         "Maximum worker count",
				MarkdownDescription: "Maximum worker count",
			},
			"min_workers": schema.Int64Attribute{
				Required:            true,
				Description:         "Minimum worker count",
				MarkdownDescription: "Minimum worker count",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the cluster being created",
				MarkdownDescription: "Name of the cluster being created",
			},
			"private_link_cluster": schema.BoolAttribute{
				Required:            true,
				Description:         "Private Link Enabled",
				MarkdownDescription: "Private Link Enabled",
			},
			"processing_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Cluster query processing mode",
				MarkdownDescription: "Cluster query processing mode",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"Batch",
						"WarpSpeed",
					),
				},
			},
			"result_cache_default_visibility_seconds": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Default visibility for resultset caching (in seconds)",
				MarkdownDescription: "Default visibility for resultset caching (in seconds)",
			},
			"result_cache_enabled": schema.BoolAttribute{
				Required:            true,
				Description:         "Enable/Disable resultset caching",
				MarkdownDescription: "Enable/Disable resultset caching",
			},
			"trino_uri": schema.StringAttribute{
				Computed:            true,
				Description:         "Connection URL (read only)",
				MarkdownDescription: "Connection URL (read only)",
			},
			"warp_resiliency_enabled": schema.BoolAttribute{
				Required:            true,
				Description:         "Enable/Disable warp resiliency",
				MarkdownDescription: "Enable/Disable warp resiliency",
			},
			"warp_speed_cluster": schema.BoolAttribute{
				Computed:            true,
				Description:         "Supports warp speed mode (read only)",
				MarkdownDescription: "Supports warp speed mode (read only)",
			},
		},
	}
}

type ClusterModel struct {
	BatchCluster                        types.Bool   `tfsdk:"batch_cluster"`
	CatalogRefs                         types.List   `tfsdk:"catalog_refs"`
	CloudRegionId                       types.String `tfsdk:"cloud_region_id"`
	ClusterId                           types.String `tfsdk:"cluster_id"`
	ClusterState                        types.String `tfsdk:"cluster_state"`
	Id                                  types.String `tfsdk:"id"`
	IdleStopMinutes                     types.Int64  `tfsdk:"idle_stop_minutes"`
	MaxWorkers                          types.Int64  `tfsdk:"max_workers"`
	MinWorkers                          types.Int64  `tfsdk:"min_workers"`
	Name                                types.String `tfsdk:"name"`
	PrivateLinkCluster                  types.Bool   `tfsdk:"private_link_cluster"`
	ProcessingMode                      types.String `tfsdk:"processing_mode"`
	ResultCacheDefaultVisibilitySeconds types.Int64  `tfsdk:"result_cache_default_visibility_seconds"`
	ResultCacheEnabled                  types.Bool   `tfsdk:"result_cache_enabled"`
	TrinoUri                            types.String `tfsdk:"trino_uri"`
	WarpResiliencyEnabled               types.Bool   `tfsdk:"warp_resiliency_enabled"`
	WarpSpeedCluster                    types.Bool   `tfsdk:"warp_speed_cluster"`
}
