// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_row_filter

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RowFilterResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created": schema.StringAttribute{
				Computed:            true,
				Description:         "Created on (read only)",
				MarkdownDescription: "Created on (read only)",
			},
			"description": schema.StringAttribute{
				Required:            true,
				Description:         "Description (read only)",
				MarkdownDescription: "Description (read only)",
			},
			"expression": schema.StringAttribute{
				Required:            true,
				Description:         "Row filter expression (read only)",
				MarkdownDescription: "Row filter expression (read only)",
			},
			"modified": schema.StringAttribute{
				Computed:            true,
				Description:         "Modified on (read only)",
				MarkdownDescription: "Modified on (read only)",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Row filter name (read only)",
				MarkdownDescription: "Row filter name (read only)",
			},
			"row_filter_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Row Filter ID (read only)",
				MarkdownDescription: "Row Filter ID (read only)",
			},
		},
	}
}

type RowFilterModel struct {
	Created     types.String `tfsdk:"created"`
	Description types.String `tfsdk:"description"`
	Expression  types.String `tfsdk:"expression"`
	Modified    types.String `tfsdk:"modified"`
	Name        types.String `tfsdk:"name"`
	RowFilterId types.String `tfsdk:"row_filter_id"`
}
