// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_sqlserver_catalog

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SqlserverCatalogResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"catalog_id": schema.StringAttribute{
				Computed:            true,
				Description:         "SQL Server catalog identifier (read only)",
				MarkdownDescription: "SQL Server catalog identifier (read only)",
			},
			"cloud_kind": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "SQL Server cloud kind. Defaults to AWS.",
				MarkdownDescription: "SQL Server cloud kind. Defaults to AWS.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"AWS",
						"AZURE",
						"GCP",
					),
				},
			},
			"database_name": schema.StringAttribute{
				Required:            true,
				Description:         "SQL Server database name",
				MarkdownDescription: "SQL Server database name",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Catalog description",
				MarkdownDescription: "Catalog description",
			},
			"endpoint": schema.StringAttribute{
				Required:            true,
				Description:         "SQL Server database endpoint",
				MarkdownDescription: "SQL Server database endpoint",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Catalog name",
				MarkdownDescription: "Catalog name",
			},
			"password": schema.StringAttribute{
				Required:            true,
				Description:         "SQL Server database password",
				MarkdownDescription: "SQL Server database password",
			},
			"port": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "SQL Server database port. Defaults to 1433.",
				MarkdownDescription: "SQL Server database port. Defaults to 1433.",
			},
			"read_only": schema.BoolAttribute{
				Required:            true,
				Description:         "Is catalog read only",
				MarkdownDescription: "Is catalog read only",
			},
			"ssh_tunnel_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "SSH tunnel identifier",
				MarkdownDescription: "SSH tunnel identifier",
			},
			"username": schema.StringAttribute{
				Required:            true,
				Description:         "SQL Server database username",
				MarkdownDescription: "SQL Server database username",
			},
			"validate": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Validate catalog configuration before creation",
				MarkdownDescription: "Validate catalog configuration before creation",
			},
		},
	}
}

type SqlserverCatalogModel struct {
	CatalogId    types.String `tfsdk:"catalog_id"`
	CloudKind    types.String `tfsdk:"cloud_kind"`
	DatabaseName types.String `tfsdk:"database_name"`
	Description  types.String `tfsdk:"description"`
	Endpoint     types.String `tfsdk:"endpoint"`
	Name         types.String `tfsdk:"name"`
	Password     types.String `tfsdk:"password"`
	Port         types.Int64  `tfsdk:"port"`
	ReadOnly     types.Bool   `tfsdk:"read_only"`
	SshTunnelId  types.String `tfsdk:"ssh_tunnel_id"`
	Username     types.String `tfsdk:"username"`
	Validate     types.Bool   `tfsdk:"validate"`
}
