// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_snowflake_catalog

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SnowflakeCatalogDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_identifier": schema.StringAttribute{
				Computed:            true,
				Description:         "Snowflake account identifier",
				MarkdownDescription: "Snowflake account identifier",
			},
			"authentication_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Snowflake authentication type",
				MarkdownDescription: "Snowflake authentication type",
			},
			"catalog_id": schema.StringAttribute{
				Required:            true,
				Description:         "A catalog connecting to Snowflake",
				MarkdownDescription: "A catalog connecting to Snowflake",
			},
			"cloud_kind": schema.StringAttribute{
				Computed:            true,
				Description:         "Snowflake cloud kind. Defaults to AWS.",
				MarkdownDescription: "Snowflake cloud kind. Defaults to AWS.",
			},
			"database_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Snowflake database name",
				MarkdownDescription: "Snowflake database name",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "Catalog description",
				MarkdownDescription: "Catalog description",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Catalog name",
				MarkdownDescription: "Catalog name",
			},
			"password": schema.StringAttribute{
				Computed:            true,
				Description:         "Snowflake password",
				MarkdownDescription: "Snowflake password",
			},
			"private_key": schema.StringAttribute{
				Computed:            true,
				Description:         "Snowflake private key",
				MarkdownDescription: "Snowflake private key",
			},
			"private_key_passphrase": schema.StringAttribute{
				Computed:            true,
				Description:         "Snowflake private key passphrase",
				MarkdownDescription: "Snowflake private key passphrase",
			},
			"read_only": schema.BoolAttribute{
				Computed:            true,
				Description:         "Is catalog read only",
				MarkdownDescription: "Is catalog read only",
			},
			"role": schema.StringAttribute{
				Computed:            true,
				Description:         "Snowflake role",
				MarkdownDescription: "Snowflake role",
			},
			"username": schema.StringAttribute{
				Computed:            true,
				Description:         "Snowflake username",
				MarkdownDescription: "Snowflake username",
			},
			"validate": schema.BoolAttribute{
				Computed:            true,
				Description:         "Validate catalog configuration before creation",
				MarkdownDescription: "Validate catalog configuration before creation",
			},
			"warehouse": schema.StringAttribute{
				Computed:            true,
				Description:         "Snowflake warehouse name",
				MarkdownDescription: "Snowflake warehouse name",
			},
		},
	}
}

type SnowflakeCatalogModel struct {
	AccountIdentifier    types.String `tfsdk:"account_identifier"`
	AuthenticationType   types.String `tfsdk:"authentication_type"`
	CatalogId            types.String `tfsdk:"catalog_id"`
	CloudKind            types.String `tfsdk:"cloud_kind"`
	DatabaseName         types.String `tfsdk:"database_name"`
	Description          types.String `tfsdk:"description"`
	Name                 types.String `tfsdk:"name"`
	Password             types.String `tfsdk:"password"`
	PrivateKey           types.String `tfsdk:"private_key"`
	PrivateKeyPassphrase types.String `tfsdk:"private_key_passphrase"`
	ReadOnly             types.Bool   `tfsdk:"read_only"`
	Role                 types.String `tfsdk:"role"`
	Username             types.String `tfsdk:"username"`
	Validate             types.Bool   `tfsdk:"validate"`
	Warehouse            types.String `tfsdk:"warehouse"`
}
