// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_clusters

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ClustersDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"result": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"batch_cluster": schema.BoolAttribute{
							Computed:            true,
							Description:         "Supports resource intensive query processing mode (read only)",
							MarkdownDescription: "Supports resource intensive query processing mode (read only)",
						},
						"catalog_refs": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "Cluster attached catalog IDs (read only)",
							MarkdownDescription: "Cluster attached catalog IDs (read only)",
						},
						"cloud_region_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Cloud region ID (read only)",
							MarkdownDescription: "Cloud region ID (read only)",
						},
						"cluster_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Cluster ID (read only)",
							MarkdownDescription: "Cluster ID (read only)",
						},
						"cluster_state": schema.StringAttribute{
							Computed:            true,
							Description:         "Cluster state (read only)",
							MarkdownDescription: "Cluster state (read only)",
						},
						"idle_stop_minutes": schema.Int64Attribute{
							Computed:            true,
							Description:         "Idle stop duration (in minutes) (read only)",
							MarkdownDescription: "Idle stop duration (in minutes) (read only)",
						},
						"max_workers": schema.Int64Attribute{
							Computed:            true,
							Description:         "Maximum worker count (read only)",
							MarkdownDescription: "Maximum worker count (read only)",
						},
						"min_workers": schema.Int64Attribute{
							Computed:            true,
							Description:         "Minimum worker count (read only)",
							MarkdownDescription: "Minimum worker count (read only)",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "Cluster name (read only)",
							MarkdownDescription: "Cluster name (read only)",
						},
						"trino_uri": schema.StringAttribute{
							Computed:            true,
							Description:         "Connection URL (read only)",
							MarkdownDescription: "Connection URL (read only)",
						},
						"warp_speed_cluster": schema.BoolAttribute{
							Computed:            true,
							Description:         "Supports warp speed mode (read only)",
							MarkdownDescription: "Supports warp speed mode (read only)",
						},
					},
					CustomType: ResultType{
						ObjectType: types.ObjectType{
							AttrTypes: ResultValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "A page of results.",
				MarkdownDescription: "A page of results.",
			},
		},
	}
}

type ClustersModel struct {
	Result types.List `tfsdk:"result"`
}

var _ basetypes.ObjectTypable = ResultType{}

type ResultType struct {
	basetypes.ObjectType
}

func (t ResultType) Equal(o attr.Type) bool {
	other, ok := o.(ResultType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ResultType) String() string {
	return "ResultType"
}

func (t ResultType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	batchClusterAttribute, ok := attributes["batch_cluster"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`batch_cluster is missing from object`)

		return nil, diags
	}

	batchClusterVal, ok := batchClusterAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`batch_cluster expected to be basetypes.BoolValue, was: %T`, batchClusterAttribute))
	}

	catalogRefsAttribute, ok := attributes["catalog_refs"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`catalog_refs is missing from object`)

		return nil, diags
	}

	catalogRefsVal, ok := catalogRefsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`catalog_refs expected to be basetypes.ListValue, was: %T`, catalogRefsAttribute))
	}

	cloudRegionIdAttribute, ok := attributes["cloud_region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cloud_region_id is missing from object`)

		return nil, diags
	}

	cloudRegionIdVal, ok := cloudRegionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cloud_region_id expected to be basetypes.StringValue, was: %T`, cloudRegionIdAttribute))
	}

	clusterIdAttribute, ok := attributes["cluster_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cluster_id is missing from object`)

		return nil, diags
	}

	clusterIdVal, ok := clusterIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cluster_id expected to be basetypes.StringValue, was: %T`, clusterIdAttribute))
	}

	clusterStateAttribute, ok := attributes["cluster_state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cluster_state is missing from object`)

		return nil, diags
	}

	clusterStateVal, ok := clusterStateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cluster_state expected to be basetypes.StringValue, was: %T`, clusterStateAttribute))
	}

	idleStopMinutesAttribute, ok := attributes["idle_stop_minutes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`idle_stop_minutes is missing from object`)

		return nil, diags
	}

	idleStopMinutesVal, ok := idleStopMinutesAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`idle_stop_minutes expected to be basetypes.Int64Value, was: %T`, idleStopMinutesAttribute))
	}

	maxWorkersAttribute, ok := attributes["max_workers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_workers is missing from object`)

		return nil, diags
	}

	maxWorkersVal, ok := maxWorkersAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_workers expected to be basetypes.Int64Value, was: %T`, maxWorkersAttribute))
	}

	minWorkersAttribute, ok := attributes["min_workers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`min_workers is missing from object`)

		return nil, diags
	}

	minWorkersVal, ok := minWorkersAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`min_workers expected to be basetypes.Int64Value, was: %T`, minWorkersAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	trinoUriAttribute, ok := attributes["trino_uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`trino_uri is missing from object`)

		return nil, diags
	}

	trinoUriVal, ok := trinoUriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`trino_uri expected to be basetypes.StringValue, was: %T`, trinoUriAttribute))
	}

	warpSpeedClusterAttribute, ok := attributes["warp_speed_cluster"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`warp_speed_cluster is missing from object`)

		return nil, diags
	}

	warpSpeedClusterVal, ok := warpSpeedClusterAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`warp_speed_cluster expected to be basetypes.BoolValue, was: %T`, warpSpeedClusterAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ResultValue{
		BatchCluster:     batchClusterVal,
		CatalogRefs:      catalogRefsVal,
		CloudRegionId:    cloudRegionIdVal,
		ClusterId:        clusterIdVal,
		ClusterState:     clusterStateVal,
		IdleStopMinutes:  idleStopMinutesVal,
		MaxWorkers:       maxWorkersVal,
		MinWorkers:       minWorkersVal,
		Name:             nameVal,
		TrinoUri:         trinoUriVal,
		WarpSpeedCluster: warpSpeedClusterVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewResultValueNull() ResultValue {
	return ResultValue{
		state: attr.ValueStateNull,
	}
}

func NewResultValueUnknown() ResultValue {
	return ResultValue{
		state: attr.ValueStateUnknown,
	}
}

func NewResultValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ResultValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ResultValue Attribute Value",
				"While creating a ResultValue value, a missing attribute value was detected. "+
					"A ResultValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ResultValue Attribute Type",
				"While creating a ResultValue value, an invalid attribute value was detected. "+
					"A ResultValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ResultValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ResultValue Attribute Value",
				"While creating a ResultValue value, an extra attribute value was detected. "+
					"A ResultValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ResultValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	batchClusterAttribute, ok := attributes["batch_cluster"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`batch_cluster is missing from object`)

		return NewResultValueUnknown(), diags
	}

	batchClusterVal, ok := batchClusterAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`batch_cluster expected to be basetypes.BoolValue, was: %T`, batchClusterAttribute))
	}

	catalogRefsAttribute, ok := attributes["catalog_refs"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`catalog_refs is missing from object`)

		return NewResultValueUnknown(), diags
	}

	catalogRefsVal, ok := catalogRefsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`catalog_refs expected to be basetypes.ListValue, was: %T`, catalogRefsAttribute))
	}

	cloudRegionIdAttribute, ok := attributes["cloud_region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cloud_region_id is missing from object`)

		return NewResultValueUnknown(), diags
	}

	cloudRegionIdVal, ok := cloudRegionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cloud_region_id expected to be basetypes.StringValue, was: %T`, cloudRegionIdAttribute))
	}

	clusterIdAttribute, ok := attributes["cluster_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cluster_id is missing from object`)

		return NewResultValueUnknown(), diags
	}

	clusterIdVal, ok := clusterIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cluster_id expected to be basetypes.StringValue, was: %T`, clusterIdAttribute))
	}

	clusterStateAttribute, ok := attributes["cluster_state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cluster_state is missing from object`)

		return NewResultValueUnknown(), diags
	}

	clusterStateVal, ok := clusterStateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cluster_state expected to be basetypes.StringValue, was: %T`, clusterStateAttribute))
	}

	idleStopMinutesAttribute, ok := attributes["idle_stop_minutes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`idle_stop_minutes is missing from object`)

		return NewResultValueUnknown(), diags
	}

	idleStopMinutesVal, ok := idleStopMinutesAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`idle_stop_minutes expected to be basetypes.Int64Value, was: %T`, idleStopMinutesAttribute))
	}

	maxWorkersAttribute, ok := attributes["max_workers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_workers is missing from object`)

		return NewResultValueUnknown(), diags
	}

	maxWorkersVal, ok := maxWorkersAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_workers expected to be basetypes.Int64Value, was: %T`, maxWorkersAttribute))
	}

	minWorkersAttribute, ok := attributes["min_workers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`min_workers is missing from object`)

		return NewResultValueUnknown(), diags
	}

	minWorkersVal, ok := minWorkersAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`min_workers expected to be basetypes.Int64Value, was: %T`, minWorkersAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewResultValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	trinoUriAttribute, ok := attributes["trino_uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`trino_uri is missing from object`)

		return NewResultValueUnknown(), diags
	}

	trinoUriVal, ok := trinoUriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`trino_uri expected to be basetypes.StringValue, was: %T`, trinoUriAttribute))
	}

	warpSpeedClusterAttribute, ok := attributes["warp_speed_cluster"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`warp_speed_cluster is missing from object`)

		return NewResultValueUnknown(), diags
	}

	warpSpeedClusterVal, ok := warpSpeedClusterAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`warp_speed_cluster expected to be basetypes.BoolValue, was: %T`, warpSpeedClusterAttribute))
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	return ResultValue{
		BatchCluster:     batchClusterVal,
		CatalogRefs:      catalogRefsVal,
		CloudRegionId:    cloudRegionIdVal,
		ClusterId:        clusterIdVal,
		ClusterState:     clusterStateVal,
		IdleStopMinutes:  idleStopMinutesVal,
		MaxWorkers:       maxWorkersVal,
		MinWorkers:       minWorkersVal,
		Name:             nameVal,
		TrinoUri:         trinoUriVal,
		WarpSpeedCluster: warpSpeedClusterVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewResultValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ResultValue {
	object, diags := NewResultValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewResultValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ResultType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewResultValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewResultValueUnknown(), nil
	}

	if in.IsNull() {
		return NewResultValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewResultValueMust(ResultValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ResultType) ValueType(ctx context.Context) attr.Value {
	return ResultValue{}
}

var _ basetypes.ObjectValuable = ResultValue{}

type ResultValue struct {
	BatchCluster     basetypes.BoolValue   `tfsdk:"batch_cluster"`
	CatalogRefs      basetypes.ListValue   `tfsdk:"catalog_refs"`
	CloudRegionId    basetypes.StringValue `tfsdk:"cloud_region_id"`
	ClusterId        basetypes.StringValue `tfsdk:"cluster_id"`
	ClusterState     basetypes.StringValue `tfsdk:"cluster_state"`
	IdleStopMinutes  basetypes.Int64Value  `tfsdk:"idle_stop_minutes"`
	MaxWorkers       basetypes.Int64Value  `tfsdk:"max_workers"`
	MinWorkers       basetypes.Int64Value  `tfsdk:"min_workers"`
	Name             basetypes.StringValue `tfsdk:"name"`
	TrinoUri         basetypes.StringValue `tfsdk:"trino_uri"`
	WarpSpeedCluster basetypes.BoolValue   `tfsdk:"warp_speed_cluster"`
	state            attr.ValueState
}

func (v ResultValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 11)

	var val tftypes.Value
	var err error

	attrTypes["batch_cluster"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["catalog_refs"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["cloud_region_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["cluster_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["cluster_state"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["idle_stop_minutes"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["max_workers"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["min_workers"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["trino_uri"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["warp_speed_cluster"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 11)

		val, err = v.BatchCluster.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["batch_cluster"] = val

		val, err = v.CatalogRefs.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["catalog_refs"] = val

		val, err = v.CloudRegionId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cloud_region_id"] = val

		val, err = v.ClusterId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cluster_id"] = val

		val, err = v.ClusterState.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cluster_state"] = val

		val, err = v.IdleStopMinutes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["idle_stop_minutes"] = val

		val, err = v.MaxWorkers.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["max_workers"] = val

		val, err = v.MinWorkers.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["min_workers"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.TrinoUri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["trino_uri"] = val

		val, err = v.WarpSpeedCluster.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["warp_speed_cluster"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ResultValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ResultValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ResultValue) String() string {
	return "ResultValue"
}

func (v ResultValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var catalogRefsVal basetypes.ListValue
	switch {
	case v.CatalogRefs.IsUnknown():
		catalogRefsVal = types.ListUnknown(types.StringType)
	case v.CatalogRefs.IsNull():
		catalogRefsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		catalogRefsVal, d = types.ListValue(types.StringType, v.CatalogRefs.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"batch_cluster": basetypes.BoolType{},
			"catalog_refs": basetypes.ListType{
				ElemType: types.StringType,
			},
			"cloud_region_id":    basetypes.StringType{},
			"cluster_id":         basetypes.StringType{},
			"cluster_state":      basetypes.StringType{},
			"idle_stop_minutes":  basetypes.Int64Type{},
			"max_workers":        basetypes.Int64Type{},
			"min_workers":        basetypes.Int64Type{},
			"name":               basetypes.StringType{},
			"trino_uri":          basetypes.StringType{},
			"warp_speed_cluster": basetypes.BoolType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"batch_cluster": basetypes.BoolType{},
		"catalog_refs": basetypes.ListType{
			ElemType: types.StringType,
		},
		"cloud_region_id":    basetypes.StringType{},
		"cluster_id":         basetypes.StringType{},
		"cluster_state":      basetypes.StringType{},
		"idle_stop_minutes":  basetypes.Int64Type{},
		"max_workers":        basetypes.Int64Type{},
		"min_workers":        basetypes.Int64Type{},
		"name":               basetypes.StringType{},
		"trino_uri":          basetypes.StringType{},
		"warp_speed_cluster": basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"batch_cluster":      v.BatchCluster,
			"catalog_refs":       catalogRefsVal,
			"cloud_region_id":    v.CloudRegionId,
			"cluster_id":         v.ClusterId,
			"cluster_state":      v.ClusterState,
			"idle_stop_minutes":  v.IdleStopMinutes,
			"max_workers":        v.MaxWorkers,
			"min_workers":        v.MinWorkers,
			"name":               v.Name,
			"trino_uri":          v.TrinoUri,
			"warp_speed_cluster": v.WarpSpeedCluster,
		})

	return objVal, diags
}

func (v ResultValue) Equal(o attr.Value) bool {
	other, ok := o.(ResultValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.BatchCluster.Equal(other.BatchCluster) {
		return false
	}

	if !v.CatalogRefs.Equal(other.CatalogRefs) {
		return false
	}

	if !v.CloudRegionId.Equal(other.CloudRegionId) {
		return false
	}

	if !v.ClusterId.Equal(other.ClusterId) {
		return false
	}

	if !v.ClusterState.Equal(other.ClusterState) {
		return false
	}

	if !v.IdleStopMinutes.Equal(other.IdleStopMinutes) {
		return false
	}

	if !v.MaxWorkers.Equal(other.MaxWorkers) {
		return false
	}

	if !v.MinWorkers.Equal(other.MinWorkers) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.TrinoUri.Equal(other.TrinoUri) {
		return false
	}

	if !v.WarpSpeedCluster.Equal(other.WarpSpeedCluster) {
		return false
	}

	return true
}

func (v ResultValue) Type(ctx context.Context) attr.Type {
	return ResultType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ResultValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"batch_cluster": basetypes.BoolType{},
		"catalog_refs": basetypes.ListType{
			ElemType: types.StringType,
		},
		"cloud_region_id":    basetypes.StringType{},
		"cluster_id":         basetypes.StringType{},
		"cluster_state":      basetypes.StringType{},
		"idle_stop_minutes":  basetypes.Int64Type{},
		"max_workers":        basetypes.Int64Type{},
		"min_workers":        basetypes.Int64Type{},
		"name":               basetypes.StringType{},
		"trino_uri":          basetypes.StringType{},
		"warp_speed_cluster": basetypes.BoolType{},
	}
}
