// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_gcs_catalog

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func GcsCatalogResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"catalog_id": schema.StringAttribute{
				Computed:            true,
				Description:         "GCS catalog identifier (read only)",
				MarkdownDescription: "GCS catalog identifier (read only)",
			},
			"credentials_key": schema.StringAttribute{
				Required:            true,
				Description:         "",
				MarkdownDescription: "",
			},
			"default_bucket": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "GCS bucket to use when storing data for new schemas",
				MarkdownDescription: "GCS bucket to use when storing data for new schemas",
			},
			"default_data_location": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Default location to store data for new schemas",
				MarkdownDescription: "Default location to store data for new schemas",
			},
			"default_table_format": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Default table format for new tables: ICEBERG, DELTA, or HIVE. Defaults to ICEBERG.",
				MarkdownDescription: "Default table format for new tables: ICEBERG, DELTA, or HIVE. Defaults to ICEBERG.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Catalog description",
				MarkdownDescription: "Catalog description",
			},
			"external_table_creation_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Allow creating external tables. Defaults to false.",
				MarkdownDescription: "Allow creating external tables. Defaults to false.",
			},
			"external_table_writes_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Allow writing to external tables. Defaults to false.",
				MarkdownDescription: "Allow writing to external tables. Defaults to false.",
			},
			"hive_metastore_host": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Hive metastore host url",
				MarkdownDescription: "Hive metastore host url",
			},
			"hive_metastore_port": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Hive metastore host port. Defaults to 9083.",
				MarkdownDescription: "Hive metastore host port. Defaults to 9083.",
			},
			"metastore_type": schema.StringAttribute{
				Required: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Catalog name",
				MarkdownDescription: "Catalog name",
			},
			"read_only": schema.BoolAttribute{
				Required:            true,
				Description:         "Is catalog read only",
				MarkdownDescription: "Is catalog read only",
			},
			"ssh_tunnel_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "SSH tunnel identifier",
				MarkdownDescription: "SSH tunnel identifier",
			},
			"validate": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Validate catalog configuration before creation",
				MarkdownDescription: "Validate catalog configuration before creation",
			},
		},
	}
}

type GcsCatalogModel struct {
	CatalogId                    types.String `tfsdk:"catalog_id"`
	CredentialsKey               types.String `tfsdk:"credentials_key"`
	DefaultBucket                types.String `tfsdk:"default_bucket"`
	DefaultDataLocation          types.String `tfsdk:"default_data_location"`
	DefaultTableFormat           types.String `tfsdk:"default_table_format"`
	Description                  types.String `tfsdk:"description"`
	ExternalTableCreationEnabled types.Bool   `tfsdk:"external_table_creation_enabled"`
	ExternalTableWritesEnabled   types.Bool   `tfsdk:"external_table_writes_enabled"`
	HiveMetastoreHost            types.String `tfsdk:"hive_metastore_host"`
	HiveMetastorePort            types.Int64  `tfsdk:"hive_metastore_port"`
	MetastoreType                types.String `tfsdk:"metastore_type"`
	Name                         types.String `tfsdk:"name"`
	ReadOnly                     types.Bool   `tfsdk:"read_only"`
	SshTunnelId                  types.String `tfsdk:"ssh_tunnel_id"`
	Validate                     types.Bool   `tfsdk:"validate"`
}
