// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_cassandra_catalog

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func CassandraCatalogDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"catalog_id": schema.StringAttribute{
				Required:            true,
				Description:         "A catalog connecting to Cassandra, with options for integration with AstraDB",
				MarkdownDescription: "A catalog connecting to Cassandra, with options for integration with AstraDB",
			},
			"cloud_kind": schema.StringAttribute{
				Computed:            true,
				Description:         "Cassandra cloud kind. Defaults to AWS.",
				MarkdownDescription: "Cassandra cloud kind. Defaults to AWS.",
			},
			"contact_points": schema.StringAttribute{
				Computed:            true,
				Description:         "Cassandra hosts",
				MarkdownDescription: "Cassandra hosts",
			},
			"database_id": schema.StringAttribute{
				Computed:            true,
				Description:         "AstraDB database ID",
				MarkdownDescription: "AstraDB database ID",
			},
			"deployment_type": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "Catalog description",
				MarkdownDescription: "Catalog description",
			},
			"local_datacenter": schema.StringAttribute{
				Computed:            true,
				Description:         "Local datacenter",
				MarkdownDescription: "Local datacenter",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Catalog name",
				MarkdownDescription: "Catalog name",
			},
			"password": schema.StringAttribute{
				Computed:            true,
				Description:         "Cassandra password",
				MarkdownDescription: "Cassandra password",
			},
			"port": schema.Int64Attribute{
				Computed:            true,
				Description:         "Cassandra port. Defaults to 9042.",
				MarkdownDescription: "Cassandra port. Defaults to 9042.",
			},
			"read_only": schema.BoolAttribute{
				Computed:            true,
				Description:         "Is catalog read only",
				MarkdownDescription: "Is catalog read only",
			},
			"region": schema.StringAttribute{
				Computed:            true,
				Description:         "AstraDB region",
				MarkdownDescription: "AstraDB region",
			},
			"ssh_tunnel_id": schema.StringAttribute{
				Computed:            true,
				Description:         "SSH tunnel identifier",
				MarkdownDescription: "SSH tunnel identifier",
			},
			"token": schema.StringAttribute{
				Computed:            true,
				Description:         "AstraDB token",
				MarkdownDescription: "AstraDB token",
			},
			"username": schema.StringAttribute{
				Computed:            true,
				Description:         "Cassandra username",
				MarkdownDescription: "Cassandra username",
			},
			"validate": schema.BoolAttribute{
				Computed:            true,
				Description:         "Validate catalog configuration before creation",
				MarkdownDescription: "Validate catalog configuration before creation",
			},
		},
	}
}

type CassandraCatalogModel struct {
	CatalogId       types.String `tfsdk:"catalog_id"`
	CloudKind       types.String `tfsdk:"cloud_kind"`
	ContactPoints   types.String `tfsdk:"contact_points"`
	DatabaseId      types.String `tfsdk:"database_id"`
	DeploymentType  types.String `tfsdk:"deployment_type"`
	Description     types.String `tfsdk:"description"`
	LocalDatacenter types.String `tfsdk:"local_datacenter"`
	Name            types.String `tfsdk:"name"`
	Password        types.String `tfsdk:"password"`
	Port            types.Int64  `tfsdk:"port"`
	ReadOnly        types.Bool   `tfsdk:"read_only"`
	Region          types.String `tfsdk:"region"`
	SshTunnelId     types.String `tfsdk:"ssh_tunnel_id"`
	Token           types.String `tfsdk:"token"`
	Username        types.String `tfsdk:"username"`
	Validate        types.Bool   `tfsdk:"validate"`
}
