// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_cassandra_catalog

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CassandraCatalogResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"catalog_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Cassandra catalog identifier (read only)",
				MarkdownDescription: "Cassandra catalog identifier (read only)",
			},
			"cloud_kind": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Cassandra cloud kind. Defaults to AWS.",
				MarkdownDescription: "Cassandra cloud kind. Defaults to AWS.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"AWS",
						"AZURE",
						"GCP",
					),
				},
			},
			"contact_points": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Cassandra hosts",
				MarkdownDescription: "Cassandra hosts",
			},
			"database_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "AstraDB database ID",
				MarkdownDescription: "AstraDB database ID",
			},
			"deployment_type": schema.StringAttribute{
				Required: true,
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Catalog description",
				MarkdownDescription: "Catalog description",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A catalog connecting to Cassandra, with options for integration with AstraDB",
				MarkdownDescription: "A catalog connecting to Cassandra, with options for integration with AstraDB",
			},
			"local_datacenter": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Local datacenter",
				MarkdownDescription: "Local datacenter",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Catalog name",
				MarkdownDescription: "Catalog name",
			},
			"password": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "",
				MarkdownDescription: "",
			},
			"port": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Cassandra port. Defaults to 9042.",
				MarkdownDescription: "Cassandra port. Defaults to 9042.",
			},
			"read_only": schema.BoolAttribute{
				Required:            true,
				Description:         "Is catalog read only",
				MarkdownDescription: "Is catalog read only",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "AstraDB region",
				MarkdownDescription: "AstraDB region",
			},
			"ssh_tunnel_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "SSH tunnel identifier",
				MarkdownDescription: "SSH tunnel identifier",
			},
			"token": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "",
				MarkdownDescription: "",
			},
			"username": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Cassandra username",
				MarkdownDescription: "Cassandra username",
			},
			"validate": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Validate catalog configuration before creation",
				MarkdownDescription: "Validate catalog configuration before creation",
			},
		},
	}
}

type CassandraCatalogModel struct {
	CatalogId       types.String `tfsdk:"catalog_id"`
	CloudKind       types.String `tfsdk:"cloud_kind"`
	ContactPoints   types.String `tfsdk:"contact_points"`
	DatabaseId      types.String `tfsdk:"database_id"`
	DeploymentType  types.String `tfsdk:"deployment_type"`
	Description     types.String `tfsdk:"description"`
	Id              types.String `tfsdk:"id"`
	LocalDatacenter types.String `tfsdk:"local_datacenter"`
	Name            types.String `tfsdk:"name"`
	Password        types.String `tfsdk:"password"`
	Port            types.Int64  `tfsdk:"port"`
	ReadOnly        types.Bool   `tfsdk:"read_only"`
	Region          types.String `tfsdk:"region"`
	SshTunnelId     types.String `tfsdk:"ssh_tunnel_id"`
	Token           types.String `tfsdk:"token"`
	Username        types.String `tfsdk:"username"`
	Validate        types.Bool   `tfsdk:"validate"`
}
