// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_sqlserver_catalogs

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SqlserverCatalogsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"result": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"catalog_id": schema.StringAttribute{
							Computed:            true,
							Description:         "SQL Server catalog identifier (read only)",
							MarkdownDescription: "SQL Server catalog identifier (read only)",
						},
						"cloud_kind": schema.StringAttribute{
							Computed:            true,
							Description:         "SQL Server cloud kind. Defaults to AWS.",
							MarkdownDescription: "SQL Server cloud kind. Defaults to AWS.",
						},
						"database_name": schema.StringAttribute{
							Computed:            true,
							Description:         "SQL Server database name",
							MarkdownDescription: "SQL Server database name",
						},
						"description": schema.StringAttribute{
							Computed:            true,
							Description:         "Catalog description",
							MarkdownDescription: "Catalog description",
						},
						"endpoint": schema.StringAttribute{
							Computed:            true,
							Description:         "SQL Server database endpoint",
							MarkdownDescription: "SQL Server database endpoint",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "Catalog name",
							MarkdownDescription: "Catalog name",
						},
						"password": schema.StringAttribute{
							Computed:            true,
							Description:         "SQL Server database password",
							MarkdownDescription: "SQL Server database password",
						},
						"port": schema.Int64Attribute{
							Computed:            true,
							Description:         "SQL Server database port. Defaults to 1433.",
							MarkdownDescription: "SQL Server database port. Defaults to 1433.",
						},
						"read_only": schema.BoolAttribute{
							Computed:            true,
							Description:         "Is catalog read only",
							MarkdownDescription: "Is catalog read only",
						},
						"ssh_tunnel_id": schema.StringAttribute{
							Computed:            true,
							Description:         "SSH tunnel identifier",
							MarkdownDescription: "SSH tunnel identifier",
						},
						"username": schema.StringAttribute{
							Computed:            true,
							Description:         "SQL Server database username",
							MarkdownDescription: "SQL Server database username",
						},
						"validate": schema.BoolAttribute{
							Computed:            true,
							Description:         "Validate catalog configuration before creation",
							MarkdownDescription: "Validate catalog configuration before creation",
						},
					},
					CustomType: ResultType{
						ObjectType: types.ObjectType{
							AttrTypes: ResultValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "A page of results.",
				MarkdownDescription: "A page of results.",
			},
		},
	}
}

type SqlserverCatalogsModel struct {
	Result types.List `tfsdk:"result"`
}

var _ basetypes.ObjectTypable = ResultType{}

type ResultType struct {
	basetypes.ObjectType
}

func (t ResultType) Equal(o attr.Type) bool {
	other, ok := o.(ResultType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ResultType) String() string {
	return "ResultType"
}

func (t ResultType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	catalogIdAttribute, ok := attributes["catalog_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`catalog_id is missing from object`)

		return nil, diags
	}

	catalogIdVal, ok := catalogIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`catalog_id expected to be basetypes.StringValue, was: %T`, catalogIdAttribute))
	}

	cloudKindAttribute, ok := attributes["cloud_kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cloud_kind is missing from object`)

		return nil, diags
	}

	cloudKindVal, ok := cloudKindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cloud_kind expected to be basetypes.StringValue, was: %T`, cloudKindAttribute))
	}

	databaseNameAttribute, ok := attributes["database_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`database_name is missing from object`)

		return nil, diags
	}

	databaseNameVal, ok := databaseNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`database_name expected to be basetypes.StringValue, was: %T`, databaseNameAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	endpointAttribute, ok := attributes["endpoint"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`endpoint is missing from object`)

		return nil, diags
	}

	endpointVal, ok := endpointAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`endpoint expected to be basetypes.StringValue, was: %T`, endpointAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	passwordAttribute, ok := attributes["password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password is missing from object`)

		return nil, diags
	}

	passwordVal, ok := passwordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password expected to be basetypes.StringValue, was: %T`, passwordAttribute))
	}

	portAttribute, ok := attributes["port"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`port is missing from object`)

		return nil, diags
	}

	portVal, ok := portAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`port expected to be basetypes.Int64Value, was: %T`, portAttribute))
	}

	readOnlyAttribute, ok := attributes["read_only"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`read_only is missing from object`)

		return nil, diags
	}

	readOnlyVal, ok := readOnlyAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`read_only expected to be basetypes.BoolValue, was: %T`, readOnlyAttribute))
	}

	sshTunnelIdAttribute, ok := attributes["ssh_tunnel_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ssh_tunnel_id is missing from object`)

		return nil, diags
	}

	sshTunnelIdVal, ok := sshTunnelIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ssh_tunnel_id expected to be basetypes.StringValue, was: %T`, sshTunnelIdAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return nil, diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	validateAttribute, ok := attributes["validate"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`validate is missing from object`)

		return nil, diags
	}

	validateVal, ok := validateAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`validate expected to be basetypes.BoolValue, was: %T`, validateAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ResultValue{
		CatalogId:    catalogIdVal,
		CloudKind:    cloudKindVal,
		DatabaseName: databaseNameVal,
		Description:  descriptionVal,
		Endpoint:     endpointVal,
		Name:         nameVal,
		Password:     passwordVal,
		Port:         portVal,
		ReadOnly:     readOnlyVal,
		SshTunnelId:  sshTunnelIdVal,
		Username:     usernameVal,
		Validate:     validateVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewResultValueNull() ResultValue {
	return ResultValue{
		state: attr.ValueStateNull,
	}
}

func NewResultValueUnknown() ResultValue {
	return ResultValue{
		state: attr.ValueStateUnknown,
	}
}

func NewResultValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ResultValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ResultValue Attribute Value",
				"While creating a ResultValue value, a missing attribute value was detected. "+
					"A ResultValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ResultValue Attribute Type",
				"While creating a ResultValue value, an invalid attribute value was detected. "+
					"A ResultValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ResultValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ResultValue Attribute Value",
				"While creating a ResultValue value, an extra attribute value was detected. "+
					"A ResultValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ResultValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	catalogIdAttribute, ok := attributes["catalog_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`catalog_id is missing from object`)

		return NewResultValueUnknown(), diags
	}

	catalogIdVal, ok := catalogIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`catalog_id expected to be basetypes.StringValue, was: %T`, catalogIdAttribute))
	}

	cloudKindAttribute, ok := attributes["cloud_kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cloud_kind is missing from object`)

		return NewResultValueUnknown(), diags
	}

	cloudKindVal, ok := cloudKindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cloud_kind expected to be basetypes.StringValue, was: %T`, cloudKindAttribute))
	}

	databaseNameAttribute, ok := attributes["database_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`database_name is missing from object`)

		return NewResultValueUnknown(), diags
	}

	databaseNameVal, ok := databaseNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`database_name expected to be basetypes.StringValue, was: %T`, databaseNameAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewResultValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	endpointAttribute, ok := attributes["endpoint"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`endpoint is missing from object`)

		return NewResultValueUnknown(), diags
	}

	endpointVal, ok := endpointAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`endpoint expected to be basetypes.StringValue, was: %T`, endpointAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewResultValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	passwordAttribute, ok := attributes["password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password is missing from object`)

		return NewResultValueUnknown(), diags
	}

	passwordVal, ok := passwordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password expected to be basetypes.StringValue, was: %T`, passwordAttribute))
	}

	portAttribute, ok := attributes["port"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`port is missing from object`)

		return NewResultValueUnknown(), diags
	}

	portVal, ok := portAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`port expected to be basetypes.Int64Value, was: %T`, portAttribute))
	}

	readOnlyAttribute, ok := attributes["read_only"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`read_only is missing from object`)

		return NewResultValueUnknown(), diags
	}

	readOnlyVal, ok := readOnlyAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`read_only expected to be basetypes.BoolValue, was: %T`, readOnlyAttribute))
	}

	sshTunnelIdAttribute, ok := attributes["ssh_tunnel_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ssh_tunnel_id is missing from object`)

		return NewResultValueUnknown(), diags
	}

	sshTunnelIdVal, ok := sshTunnelIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ssh_tunnel_id expected to be basetypes.StringValue, was: %T`, sshTunnelIdAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return NewResultValueUnknown(), diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	validateAttribute, ok := attributes["validate"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`validate is missing from object`)

		return NewResultValueUnknown(), diags
	}

	validateVal, ok := validateAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`validate expected to be basetypes.BoolValue, was: %T`, validateAttribute))
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	return ResultValue{
		CatalogId:    catalogIdVal,
		CloudKind:    cloudKindVal,
		DatabaseName: databaseNameVal,
		Description:  descriptionVal,
		Endpoint:     endpointVal,
		Name:         nameVal,
		Password:     passwordVal,
		Port:         portVal,
		ReadOnly:     readOnlyVal,
		SshTunnelId:  sshTunnelIdVal,
		Username:     usernameVal,
		Validate:     validateVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewResultValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ResultValue {
	object, diags := NewResultValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewResultValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ResultType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewResultValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewResultValueUnknown(), nil
	}

	if in.IsNull() {
		return NewResultValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewResultValueMust(ResultValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ResultType) ValueType(ctx context.Context) attr.Value {
	return ResultValue{}
}

var _ basetypes.ObjectValuable = ResultValue{}

type ResultValue struct {
	CatalogId    basetypes.StringValue `tfsdk:"catalog_id"`
	CloudKind    basetypes.StringValue `tfsdk:"cloud_kind"`
	DatabaseName basetypes.StringValue `tfsdk:"database_name"`
	Description  basetypes.StringValue `tfsdk:"description"`
	Endpoint     basetypes.StringValue `tfsdk:"endpoint"`
	Name         basetypes.StringValue `tfsdk:"name"`
	Password     basetypes.StringValue `tfsdk:"password"`
	Port         basetypes.Int64Value  `tfsdk:"port"`
	ReadOnly     basetypes.BoolValue   `tfsdk:"read_only"`
	SshTunnelId  basetypes.StringValue `tfsdk:"ssh_tunnel_id"`
	Username     basetypes.StringValue `tfsdk:"username"`
	Validate     basetypes.BoolValue   `tfsdk:"validate"`
	state        attr.ValueState
}

func (v ResultValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 12)

	var val tftypes.Value
	var err error

	attrTypes["catalog_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["cloud_kind"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["database_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["endpoint"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["password"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["port"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["read_only"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["ssh_tunnel_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["username"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["validate"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 12)

		val, err = v.CatalogId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["catalog_id"] = val

		val, err = v.CloudKind.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cloud_kind"] = val

		val, err = v.DatabaseName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["database_name"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Endpoint.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["endpoint"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Password.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["password"] = val

		val, err = v.Port.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["port"] = val

		val, err = v.ReadOnly.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["read_only"] = val

		val, err = v.SshTunnelId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ssh_tunnel_id"] = val

		val, err = v.Username.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["username"] = val

		val, err = v.Validate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["validate"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ResultValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ResultValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ResultValue) String() string {
	return "ResultValue"
}

func (v ResultValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"catalog_id":    basetypes.StringType{},
		"cloud_kind":    basetypes.StringType{},
		"database_name": basetypes.StringType{},
		"description":   basetypes.StringType{},
		"endpoint":      basetypes.StringType{},
		"name":          basetypes.StringType{},
		"password":      basetypes.StringType{},
		"port":          basetypes.Int64Type{},
		"read_only":     basetypes.BoolType{},
		"ssh_tunnel_id": basetypes.StringType{},
		"username":      basetypes.StringType{},
		"validate":      basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"catalog_id":    v.CatalogId,
			"cloud_kind":    v.CloudKind,
			"database_name": v.DatabaseName,
			"description":   v.Description,
			"endpoint":      v.Endpoint,
			"name":          v.Name,
			"password":      v.Password,
			"port":          v.Port,
			"read_only":     v.ReadOnly,
			"ssh_tunnel_id": v.SshTunnelId,
			"username":      v.Username,
			"validate":      v.Validate,
		})

	return objVal, diags
}

func (v ResultValue) Equal(o attr.Value) bool {
	other, ok := o.(ResultValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CatalogId.Equal(other.CatalogId) {
		return false
	}

	if !v.CloudKind.Equal(other.CloudKind) {
		return false
	}

	if !v.DatabaseName.Equal(other.DatabaseName) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Endpoint.Equal(other.Endpoint) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Password.Equal(other.Password) {
		return false
	}

	if !v.Port.Equal(other.Port) {
		return false
	}

	if !v.ReadOnly.Equal(other.ReadOnly) {
		return false
	}

	if !v.SshTunnelId.Equal(other.SshTunnelId) {
		return false
	}

	if !v.Username.Equal(other.Username) {
		return false
	}

	if !v.Validate.Equal(other.Validate) {
		return false
	}

	return true
}

func (v ResultValue) Type(ctx context.Context) attr.Type {
	return ResultType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ResultValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"catalog_id":    basetypes.StringType{},
		"cloud_kind":    basetypes.StringType{},
		"database_name": basetypes.StringType{},
		"description":   basetypes.StringType{},
		"endpoint":      basetypes.StringType{},
		"name":          basetypes.StringType{},
		"password":      basetypes.StringType{},
		"port":          basetypes.Int64Type{},
		"read_only":     basetypes.BoolType{},
		"ssh_tunnel_id": basetypes.StringType{},
		"username":      basetypes.StringType{},
		"validate":      basetypes.BoolType{},
	}
}
