// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_cross_account_iam_roles

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func CrossAccountIamRolesDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"result": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"alias_name": schema.StringAttribute{
							Computed:            true,
							Description:         "AWS IAM role alias name (read only)",
							MarkdownDescription: "AWS IAM role alias name (read only)",
						},
						"aws_iam_arn": schema.StringAttribute{
							Computed:            true,
							Description:         "AWS IAM role ARN (read only)",
							MarkdownDescription: "AWS IAM role ARN (read only)",
						},
						"dependants": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "List of catalogs or ingest sources attached to the role (read only)",
							MarkdownDescription: "List of catalogs or ingest sources attached to the role (read only)",
						},
					},
					CustomType: ResultType{
						ObjectType: types.ObjectType{
							AttrTypes: ResultValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "A page of results.",
				MarkdownDescription: "A page of results.",
			},
		},
	}
}

type CrossAccountIamRolesModel struct {
	Result types.List `tfsdk:"result"`
}

var _ basetypes.ObjectTypable = ResultType{}

type ResultType struct {
	basetypes.ObjectType
}

func (t ResultType) Equal(o attr.Type) bool {
	other, ok := o.(ResultType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ResultType) String() string {
	return "ResultType"
}

func (t ResultType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	aliasNameAttribute, ok := attributes["alias_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alias_name is missing from object`)

		return nil, diags
	}

	aliasNameVal, ok := aliasNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alias_name expected to be basetypes.StringValue, was: %T`, aliasNameAttribute))
	}

	awsIamArnAttribute, ok := attributes["aws_iam_arn"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`aws_iam_arn is missing from object`)

		return nil, diags
	}

	awsIamArnVal, ok := awsIamArnAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`aws_iam_arn expected to be basetypes.StringValue, was: %T`, awsIamArnAttribute))
	}

	dependantsAttribute, ok := attributes["dependants"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dependants is missing from object`)

		return nil, diags
	}

	dependantsVal, ok := dependantsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dependants expected to be basetypes.ListValue, was: %T`, dependantsAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ResultValue{
		AliasName:  aliasNameVal,
		AwsIamArn:  awsIamArnVal,
		Dependants: dependantsVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewResultValueNull() ResultValue {
	return ResultValue{
		state: attr.ValueStateNull,
	}
}

func NewResultValueUnknown() ResultValue {
	return ResultValue{
		state: attr.ValueStateUnknown,
	}
}

func NewResultValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ResultValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ResultValue Attribute Value",
				"While creating a ResultValue value, a missing attribute value was detected. "+
					"A ResultValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ResultValue Attribute Type",
				"While creating a ResultValue value, an invalid attribute value was detected. "+
					"A ResultValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ResultValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ResultValue Attribute Value",
				"While creating a ResultValue value, an extra attribute value was detected. "+
					"A ResultValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ResultValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	aliasNameAttribute, ok := attributes["alias_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alias_name is missing from object`)

		return NewResultValueUnknown(), diags
	}

	aliasNameVal, ok := aliasNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alias_name expected to be basetypes.StringValue, was: %T`, aliasNameAttribute))
	}

	awsIamArnAttribute, ok := attributes["aws_iam_arn"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`aws_iam_arn is missing from object`)

		return NewResultValueUnknown(), diags
	}

	awsIamArnVal, ok := awsIamArnAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`aws_iam_arn expected to be basetypes.StringValue, was: %T`, awsIamArnAttribute))
	}

	dependantsAttribute, ok := attributes["dependants"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dependants is missing from object`)

		return NewResultValueUnknown(), diags
	}

	dependantsVal, ok := dependantsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dependants expected to be basetypes.ListValue, was: %T`, dependantsAttribute))
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	return ResultValue{
		AliasName:  aliasNameVal,
		AwsIamArn:  awsIamArnVal,
		Dependants: dependantsVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewResultValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ResultValue {
	object, diags := NewResultValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewResultValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ResultType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewResultValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewResultValueUnknown(), nil
	}

	if in.IsNull() {
		return NewResultValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewResultValueMust(ResultValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ResultType) ValueType(ctx context.Context) attr.Value {
	return ResultValue{}
}

var _ basetypes.ObjectValuable = ResultValue{}

type ResultValue struct {
	AliasName  basetypes.StringValue `tfsdk:"alias_name"`
	AwsIamArn  basetypes.StringValue `tfsdk:"aws_iam_arn"`
	Dependants basetypes.ListValue   `tfsdk:"dependants"`
	state      attr.ValueState
}

func (v ResultValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["alias_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["aws_iam_arn"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["dependants"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.AliasName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["alias_name"] = val

		val, err = v.AwsIamArn.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["aws_iam_arn"] = val

		val, err = v.Dependants.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dependants"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ResultValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ResultValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ResultValue) String() string {
	return "ResultValue"
}

func (v ResultValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var dependantsVal basetypes.ListValue
	switch {
	case v.Dependants.IsUnknown():
		dependantsVal = types.ListUnknown(types.StringType)
	case v.Dependants.IsNull():
		dependantsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		dependantsVal, d = types.ListValue(types.StringType, v.Dependants.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"alias_name":  basetypes.StringType{},
			"aws_iam_arn": basetypes.StringType{},
			"dependants": basetypes.ListType{
				ElemType: types.StringType,
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"alias_name":  basetypes.StringType{},
		"aws_iam_arn": basetypes.StringType{},
		"dependants": basetypes.ListType{
			ElemType: types.StringType,
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"alias_name":  v.AliasName,
			"aws_iam_arn": v.AwsIamArn,
			"dependants":  dependantsVal,
		})

	return objVal, diags
}

func (v ResultValue) Equal(o attr.Value) bool {
	other, ok := o.(ResultValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AliasName.Equal(other.AliasName) {
		return false
	}

	if !v.AwsIamArn.Equal(other.AwsIamArn) {
		return false
	}

	if !v.Dependants.Equal(other.Dependants) {
		return false
	}

	return true
}

func (v ResultValue) Type(ctx context.Context) attr.Type {
	return ResultType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ResultValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"alias_name":  basetypes.StringType{},
		"aws_iam_arn": basetypes.StringType{},
		"dependants": basetypes.ListType{
			ElemType: types.StringType,
		},
	}
}
