// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_column_mask

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ColumnMaskResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"column_mask_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Column Mask ID (read only)",
				MarkdownDescription: "Column Mask ID (read only)",
			},
			"column_mask_type": schema.StringAttribute{
				Required:            true,
				Description:         "Column mask type (read only)",
				MarkdownDescription: "Column mask type (read only)",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"Any",
						"Integer",
						"Boolean",
						"Date",
						"Decimal",
						"Real",
						"Double",
						"Timestamp",
						"TimestampWithTimeZone",
						"Time",
						"TimeWithTimeZone",
						"Varbinary",
						"Varchar",
					),
				},
			},
			"created": schema.StringAttribute{
				Computed:            true,
				Description:         "Created on (read only)",
				MarkdownDescription: "Created on (read only)",
			},
			"description": schema.StringAttribute{
				Required:            true,
				Description:         "Description (read only)",
				MarkdownDescription: "Description (read only)",
			},
			"expression": schema.StringAttribute{
				Required:            true,
				Description:         "Column mask expression (read only)",
				MarkdownDescription: "Column mask expression (read only)",
			},
			"modified": schema.StringAttribute{
				Computed:            true,
				Description:         "Modified on (read only)",
				MarkdownDescription: "Modified on (read only)",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Column mask name (read only)",
				MarkdownDescription: "Column mask name (read only)",
			},
		},
	}
}

type ColumnMaskModel struct {
	ColumnMaskId   types.String `tfsdk:"column_mask_id"`
	ColumnMaskType types.String `tfsdk:"column_mask_type"`
	Created        types.String `tfsdk:"created"`
	Description    types.String `tfsdk:"description"`
	Expression     types.String `tfsdk:"expression"`
	Modified       types.String `tfsdk:"modified"`
	Name           types.String `tfsdk:"name"`
}
