// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_cassandra_catalog_validation

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func CassandraCatalogValidationDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"catalog_id": schema.StringAttribute{
				Required:            true,
				Description:         "A catalog connecting to Cassandra, with options for integration with AstraDB",
				MarkdownDescription: "A catalog connecting to Cassandra, with options for integration with AstraDB",
			},
			"error_messages": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "Errors found in the validation process (read only)",
				MarkdownDescription: "Errors found in the validation process (read only)",
			},
			"info_messages": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "Additional information found in the validation process (read only)",
				MarkdownDescription: "Additional information found in the validation process (read only)",
			},
			"validation_successful": schema.BoolAttribute{
				Computed:            true,
				Description:         "Is the catalog readable (read only)",
				MarkdownDescription: "Is the catalog readable (read only)",
			},
			"warning_messages": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "Warnings found in the validation process (read only)",
				MarkdownDescription: "Warnings found in the validation process (read only)",
			},
		},
	}
}

type CassandraCatalogValidationModel struct {
	CatalogId            types.String `tfsdk:"catalog_id"`
	ErrorMessages        types.List   `tfsdk:"error_messages"`
	InfoMessages         types.List   `tfsdk:"info_messages"`
	ValidationSuccessful types.Bool   `tfsdk:"validation_successful"`
	WarningMessages      types.List   `tfsdk:"warning_messages"`
}
