// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_service_accounts

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ServiceAccountsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"result": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"additional_role_ids": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "Additional roles (read only)",
							MarkdownDescription: "Additional roles (read only)",
						},
						"passwords": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"created": schema.StringAttribute{
										Computed:            true,
										Description:         "Creation time (read only)",
										MarkdownDescription: "Creation time (read only)",
									},
									"description": schema.StringAttribute{
										Computed:            true,
										Description:         "Description (read only)",
										MarkdownDescription: "Description (read only)",
									},
									"last_login": schema.StringAttribute{
										Computed:            true,
										Description:         "Last login time (read only)",
										MarkdownDescription: "Last login time (read only)",
									},
									"password": schema.StringAttribute{
										Computed:            true,
										Description:         "Service account password (read only)",
										MarkdownDescription: "Service account password (read only)",
									},
									"password_prefix": schema.StringAttribute{
										Computed:            true,
										Description:         "Service account password prefix (read only)",
										MarkdownDescription: "Service account password prefix (read only)",
									},
									"service_account_password_id": schema.StringAttribute{
										Computed:            true,
										Description:         "Service account password ID (read only)",
										MarkdownDescription: "Service account password ID (read only)",
									},
								},
								CustomType: PasswordsType{
									ObjectType: types.ObjectType{
										AttrTypes: PasswordsValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed:            true,
							Description:         "Passwords (read only)",
							MarkdownDescription: "Passwords (read only)",
						},
						"role_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Default role (read only)",
							MarkdownDescription: "Default role (read only)",
						},
						"service_account_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Service account ID (read only)",
							MarkdownDescription: "Service account ID (read only)",
						},
						"user_name": schema.StringAttribute{
							Computed:            true,
							Description:         "Service account user name (read only)",
							MarkdownDescription: "Service account user name (read only)",
						},
					},
					CustomType: ResultType{
						ObjectType: types.ObjectType{
							AttrTypes: ResultValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "A page of results.",
				MarkdownDescription: "A page of results.",
			},
		},
	}
}

type ServiceAccountsModel struct {
	Result types.List `tfsdk:"result"`
}

var _ basetypes.ObjectTypable = ResultType{}

type ResultType struct {
	basetypes.ObjectType
}

func (t ResultType) Equal(o attr.Type) bool {
	other, ok := o.(ResultType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ResultType) String() string {
	return "ResultType"
}

func (t ResultType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	additionalRoleIdsAttribute, ok := attributes["additional_role_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`additional_role_ids is missing from object`)

		return nil, diags
	}

	additionalRoleIdsVal, ok := additionalRoleIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`additional_role_ids expected to be basetypes.ListValue, was: %T`, additionalRoleIdsAttribute))
	}

	passwordsAttribute, ok := attributes["passwords"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`passwords is missing from object`)

		return nil, diags
	}

	passwordsVal, ok := passwordsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`passwords expected to be basetypes.ListValue, was: %T`, passwordsAttribute))
	}

	roleIdAttribute, ok := attributes["role_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_id is missing from object`)

		return nil, diags
	}

	roleIdVal, ok := roleIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_id expected to be basetypes.StringValue, was: %T`, roleIdAttribute))
	}

	serviceAccountIdAttribute, ok := attributes["service_account_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`service_account_id is missing from object`)

		return nil, diags
	}

	serviceAccountIdVal, ok := serviceAccountIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`service_account_id expected to be basetypes.StringValue, was: %T`, serviceAccountIdAttribute))
	}

	userNameAttribute, ok := attributes["user_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_name is missing from object`)

		return nil, diags
	}

	userNameVal, ok := userNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_name expected to be basetypes.StringValue, was: %T`, userNameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ResultValue{
		AdditionalRoleIds: additionalRoleIdsVal,
		Passwords:         passwordsVal,
		RoleId:            roleIdVal,
		ServiceAccountId:  serviceAccountIdVal,
		UserName:          userNameVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewResultValueNull() ResultValue {
	return ResultValue{
		state: attr.ValueStateNull,
	}
}

func NewResultValueUnknown() ResultValue {
	return ResultValue{
		state: attr.ValueStateUnknown,
	}
}

func NewResultValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ResultValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ResultValue Attribute Value",
				"While creating a ResultValue value, a missing attribute value was detected. "+
					"A ResultValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ResultValue Attribute Type",
				"While creating a ResultValue value, an invalid attribute value was detected. "+
					"A ResultValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ResultValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ResultValue Attribute Value",
				"While creating a ResultValue value, an extra attribute value was detected. "+
					"A ResultValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ResultValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	additionalRoleIdsAttribute, ok := attributes["additional_role_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`additional_role_ids is missing from object`)

		return NewResultValueUnknown(), diags
	}

	additionalRoleIdsVal, ok := additionalRoleIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`additional_role_ids expected to be basetypes.ListValue, was: %T`, additionalRoleIdsAttribute))
	}

	passwordsAttribute, ok := attributes["passwords"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`passwords is missing from object`)

		return NewResultValueUnknown(), diags
	}

	passwordsVal, ok := passwordsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`passwords expected to be basetypes.ListValue, was: %T`, passwordsAttribute))
	}

	roleIdAttribute, ok := attributes["role_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_id is missing from object`)

		return NewResultValueUnknown(), diags
	}

	roleIdVal, ok := roleIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_id expected to be basetypes.StringValue, was: %T`, roleIdAttribute))
	}

	serviceAccountIdAttribute, ok := attributes["service_account_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`service_account_id is missing from object`)

		return NewResultValueUnknown(), diags
	}

	serviceAccountIdVal, ok := serviceAccountIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`service_account_id expected to be basetypes.StringValue, was: %T`, serviceAccountIdAttribute))
	}

	userNameAttribute, ok := attributes["user_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_name is missing from object`)

		return NewResultValueUnknown(), diags
	}

	userNameVal, ok := userNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_name expected to be basetypes.StringValue, was: %T`, userNameAttribute))
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	return ResultValue{
		AdditionalRoleIds: additionalRoleIdsVal,
		Passwords:         passwordsVal,
		RoleId:            roleIdVal,
		ServiceAccountId:  serviceAccountIdVal,
		UserName:          userNameVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewResultValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ResultValue {
	object, diags := NewResultValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewResultValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ResultType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewResultValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewResultValueUnknown(), nil
	}

	if in.IsNull() {
		return NewResultValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewResultValueMust(ResultValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ResultType) ValueType(ctx context.Context) attr.Value {
	return ResultValue{}
}

var _ basetypes.ObjectValuable = ResultValue{}

type ResultValue struct {
	AdditionalRoleIds basetypes.ListValue   `tfsdk:"additional_role_ids"`
	Passwords         basetypes.ListValue   `tfsdk:"passwords"`
	RoleId            basetypes.StringValue `tfsdk:"role_id"`
	ServiceAccountId  basetypes.StringValue `tfsdk:"service_account_id"`
	UserName          basetypes.StringValue `tfsdk:"user_name"`
	state             attr.ValueState
}

func (v ResultValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["additional_role_ids"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["passwords"] = basetypes.ListType{
		ElemType: PasswordsValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["role_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["service_account_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["user_name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.AdditionalRoleIds.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["additional_role_ids"] = val

		val, err = v.Passwords.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["passwords"] = val

		val, err = v.RoleId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["role_id"] = val

		val, err = v.ServiceAccountId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["service_account_id"] = val

		val, err = v.UserName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["user_name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ResultValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ResultValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ResultValue) String() string {
	return "ResultValue"
}

func (v ResultValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	passwords := types.ListValueMust(
		PasswordsType{
			basetypes.ObjectType{
				AttrTypes: PasswordsValue{}.AttributeTypes(ctx),
			},
		},
		v.Passwords.Elements(),
	)

	if v.Passwords.IsNull() {
		passwords = types.ListNull(
			PasswordsType{
				basetypes.ObjectType{
					AttrTypes: PasswordsValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Passwords.IsUnknown() {
		passwords = types.ListUnknown(
			PasswordsType{
				basetypes.ObjectType{
					AttrTypes: PasswordsValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	var additionalRoleIdsVal basetypes.ListValue
	switch {
	case v.AdditionalRoleIds.IsUnknown():
		additionalRoleIdsVal = types.ListUnknown(types.StringType)
	case v.AdditionalRoleIds.IsNull():
		additionalRoleIdsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		additionalRoleIdsVal, d = types.ListValue(types.StringType, v.AdditionalRoleIds.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"additional_role_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"passwords": basetypes.ListType{
				ElemType: PasswordsValue{}.Type(ctx),
			},
			"role_id":            basetypes.StringType{},
			"service_account_id": basetypes.StringType{},
			"user_name":          basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"additional_role_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"passwords": basetypes.ListType{
			ElemType: PasswordsValue{}.Type(ctx),
		},
		"role_id":            basetypes.StringType{},
		"service_account_id": basetypes.StringType{},
		"user_name":          basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"additional_role_ids": additionalRoleIdsVal,
			"passwords":           passwords,
			"role_id":             v.RoleId,
			"service_account_id":  v.ServiceAccountId,
			"user_name":           v.UserName,
		})

	return objVal, diags
}

func (v ResultValue) Equal(o attr.Value) bool {
	other, ok := o.(ResultValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AdditionalRoleIds.Equal(other.AdditionalRoleIds) {
		return false
	}

	if !v.Passwords.Equal(other.Passwords) {
		return false
	}

	if !v.RoleId.Equal(other.RoleId) {
		return false
	}

	if !v.ServiceAccountId.Equal(other.ServiceAccountId) {
		return false
	}

	if !v.UserName.Equal(other.UserName) {
		return false
	}

	return true
}

func (v ResultValue) Type(ctx context.Context) attr.Type {
	return ResultType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ResultValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"additional_role_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"passwords": basetypes.ListType{
			ElemType: PasswordsValue{}.Type(ctx),
		},
		"role_id":            basetypes.StringType{},
		"service_account_id": basetypes.StringType{},
		"user_name":          basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = PasswordsType{}

type PasswordsType struct {
	basetypes.ObjectType
}

func (t PasswordsType) Equal(o attr.Type) bool {
	other, ok := o.(PasswordsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PasswordsType) String() string {
	return "PasswordsType"
}

func (t PasswordsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAttribute, ok := attributes["created"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created is missing from object`)

		return nil, diags
	}

	createdVal, ok := createdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created expected to be basetypes.StringValue, was: %T`, createdAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	lastLoginAttribute, ok := attributes["last_login"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_login is missing from object`)

		return nil, diags
	}

	lastLoginVal, ok := lastLoginAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_login expected to be basetypes.StringValue, was: %T`, lastLoginAttribute))
	}

	passwordAttribute, ok := attributes["password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password is missing from object`)

		return nil, diags
	}

	passwordVal, ok := passwordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password expected to be basetypes.StringValue, was: %T`, passwordAttribute))
	}

	passwordPrefixAttribute, ok := attributes["password_prefix"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password_prefix is missing from object`)

		return nil, diags
	}

	passwordPrefixVal, ok := passwordPrefixAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password_prefix expected to be basetypes.StringValue, was: %T`, passwordPrefixAttribute))
	}

	serviceAccountPasswordIdAttribute, ok := attributes["service_account_password_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`service_account_password_id is missing from object`)

		return nil, diags
	}

	serviceAccountPasswordIdVal, ok := serviceAccountPasswordIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`service_account_password_id expected to be basetypes.StringValue, was: %T`, serviceAccountPasswordIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PasswordsValue{
		Created:                  createdVal,
		Description:              descriptionVal,
		LastLogin:                lastLoginVal,
		Password:                 passwordVal,
		PasswordPrefix:           passwordPrefixVal,
		ServiceAccountPasswordId: serviceAccountPasswordIdVal,
		state:                    attr.ValueStateKnown,
	}, diags
}

func NewPasswordsValueNull() PasswordsValue {
	return PasswordsValue{
		state: attr.ValueStateNull,
	}
}

func NewPasswordsValueUnknown() PasswordsValue {
	return PasswordsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPasswordsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PasswordsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PasswordsValue Attribute Value",
				"While creating a PasswordsValue value, a missing attribute value was detected. "+
					"A PasswordsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PasswordsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PasswordsValue Attribute Type",
				"While creating a PasswordsValue value, an invalid attribute value was detected. "+
					"A PasswordsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PasswordsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PasswordsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PasswordsValue Attribute Value",
				"While creating a PasswordsValue value, an extra attribute value was detected. "+
					"A PasswordsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PasswordsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPasswordsValueUnknown(), diags
	}

	createdAttribute, ok := attributes["created"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created is missing from object`)

		return NewPasswordsValueUnknown(), diags
	}

	createdVal, ok := createdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created expected to be basetypes.StringValue, was: %T`, createdAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewPasswordsValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	lastLoginAttribute, ok := attributes["last_login"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_login is missing from object`)

		return NewPasswordsValueUnknown(), diags
	}

	lastLoginVal, ok := lastLoginAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_login expected to be basetypes.StringValue, was: %T`, lastLoginAttribute))
	}

	passwordAttribute, ok := attributes["password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password is missing from object`)

		return NewPasswordsValueUnknown(), diags
	}

	passwordVal, ok := passwordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password expected to be basetypes.StringValue, was: %T`, passwordAttribute))
	}

	passwordPrefixAttribute, ok := attributes["password_prefix"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password_prefix is missing from object`)

		return NewPasswordsValueUnknown(), diags
	}

	passwordPrefixVal, ok := passwordPrefixAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password_prefix expected to be basetypes.StringValue, was: %T`, passwordPrefixAttribute))
	}

	serviceAccountPasswordIdAttribute, ok := attributes["service_account_password_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`service_account_password_id is missing from object`)

		return NewPasswordsValueUnknown(), diags
	}

	serviceAccountPasswordIdVal, ok := serviceAccountPasswordIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`service_account_password_id expected to be basetypes.StringValue, was: %T`, serviceAccountPasswordIdAttribute))
	}

	if diags.HasError() {
		return NewPasswordsValueUnknown(), diags
	}

	return PasswordsValue{
		Created:                  createdVal,
		Description:              descriptionVal,
		LastLogin:                lastLoginVal,
		Password:                 passwordVal,
		PasswordPrefix:           passwordPrefixVal,
		ServiceAccountPasswordId: serviceAccountPasswordIdVal,
		state:                    attr.ValueStateKnown,
	}, diags
}

func NewPasswordsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PasswordsValue {
	object, diags := NewPasswordsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPasswordsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PasswordsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPasswordsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPasswordsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPasswordsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPasswordsValueMust(PasswordsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PasswordsType) ValueType(ctx context.Context) attr.Value {
	return PasswordsValue{}
}

var _ basetypes.ObjectValuable = PasswordsValue{}

type PasswordsValue struct {
	Created                  basetypes.StringValue `tfsdk:"created"`
	Description              basetypes.StringValue `tfsdk:"description"`
	LastLogin                basetypes.StringValue `tfsdk:"last_login"`
	Password                 basetypes.StringValue `tfsdk:"password"`
	PasswordPrefix           basetypes.StringValue `tfsdk:"password_prefix"`
	ServiceAccountPasswordId basetypes.StringValue `tfsdk:"service_account_password_id"`
	state                    attr.ValueState
}

func (v PasswordsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["created"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["last_login"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["password"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["password_prefix"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["service_account_password_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Created.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.LastLogin.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["last_login"] = val

		val, err = v.Password.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["password"] = val

		val, err = v.PasswordPrefix.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["password_prefix"] = val

		val, err = v.ServiceAccountPasswordId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["service_account_password_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PasswordsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PasswordsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PasswordsValue) String() string {
	return "PasswordsValue"
}

func (v PasswordsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"created":                     basetypes.StringType{},
		"description":                 basetypes.StringType{},
		"last_login":                  basetypes.StringType{},
		"password":                    basetypes.StringType{},
		"password_prefix":             basetypes.StringType{},
		"service_account_password_id": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created":                     v.Created,
			"description":                 v.Description,
			"last_login":                  v.LastLogin,
			"password":                    v.Password,
			"password_prefix":             v.PasswordPrefix,
			"service_account_password_id": v.ServiceAccountPasswordId,
		})

	return objVal, diags
}

func (v PasswordsValue) Equal(o attr.Value) bool {
	other, ok := o.(PasswordsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Created.Equal(other.Created) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.LastLogin.Equal(other.LastLogin) {
		return false
	}

	if !v.Password.Equal(other.Password) {
		return false
	}

	if !v.PasswordPrefix.Equal(other.PasswordPrefix) {
		return false
	}

	if !v.ServiceAccountPasswordId.Equal(other.ServiceAccountPasswordId) {
		return false
	}

	return true
}

func (v PasswordsValue) Type(ctx context.Context) attr.Type {
	return PasswordsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PasswordsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created":                     basetypes.StringType{},
		"description":                 basetypes.StringType{},
		"last_login":                  basetypes.StringType{},
		"password":                    basetypes.StringType{},
		"password_prefix":             basetypes.StringType{},
		"service_account_password_id": basetypes.StringType{},
	}
}
