// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_groups

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func GroupsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"result": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created_on": schema.StringAttribute{
							Computed:            true,
							Description:         "Creation date (read only)",
							MarkdownDescription: "Creation date (read only)",
						},
						"external_id": schema.StringAttribute{
							Computed:            true,
							Description:         "SCIM external ID (read only)",
							MarkdownDescription: "SCIM external ID (read only)",
						},
						"group_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Group ID (read only)",
							MarkdownDescription: "Group ID (read only)",
						},
						"group_name": schema.StringAttribute{
							Computed:            true,
							Description:         "Group name (read only)",
							MarkdownDescription: "Group name (read only)",
						},
						"modified_on": schema.StringAttribute{
							Computed:            true,
							Description:         "Modified date (read only)",
							MarkdownDescription: "Modified date (read only)",
						},
						"roles": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"role_id": schema.StringAttribute{
										Computed:            true,
										Description:         "Role ID (read only)",
										MarkdownDescription: "Role ID (read only)",
									},
									"role_name": schema.StringAttribute{
										Computed:            true,
										Description:         "Role name (read only)",
										MarkdownDescription: "Role name (read only)",
									},
								},
								CustomType: RolesType{
									ObjectType: types.ObjectType{
										AttrTypes: RolesValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed:            true,
							Description:         "Roles assigned to this group (read only)",
							MarkdownDescription: "Roles assigned to this group (read only)",
						},
						"users": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"email": schema.StringAttribute{
										Computed:            true,
										Description:         "User email",
										MarkdownDescription: "User email",
									},
									"user_id": schema.StringAttribute{
										Computed:            true,
										Description:         "User ID",
										MarkdownDescription: "User ID",
									},
								},
								CustomType: UsersType{
									ObjectType: types.ObjectType{
										AttrTypes: UsersValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed:            true,
							Description:         "Users directly assigned to this group (read only)",
							MarkdownDescription: "Users directly assigned to this group (read only)",
						},
					},
					CustomType: ResultType{
						ObjectType: types.ObjectType{
							AttrTypes: ResultValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "A page of results.",
				MarkdownDescription: "A page of results.",
			},
		},
	}
}

type GroupsModel struct {
	Result types.List `tfsdk:"result"`
}

var _ basetypes.ObjectTypable = ResultType{}

type ResultType struct {
	basetypes.ObjectType
}

func (t ResultType) Equal(o attr.Type) bool {
	other, ok := o.(ResultType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ResultType) String() string {
	return "ResultType"
}

func (t ResultType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdOnAttribute, ok := attributes["created_on"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_on is missing from object`)

		return nil, diags
	}

	createdOnVal, ok := createdOnAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_on expected to be basetypes.StringValue, was: %T`, createdOnAttribute))
	}

	externalIdAttribute, ok := attributes["external_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`external_id is missing from object`)

		return nil, diags
	}

	externalIdVal, ok := externalIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`external_id expected to be basetypes.StringValue, was: %T`, externalIdAttribute))
	}

	groupIdAttribute, ok := attributes["group_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group_id is missing from object`)

		return nil, diags
	}

	groupIdVal, ok := groupIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group_id expected to be basetypes.StringValue, was: %T`, groupIdAttribute))
	}

	groupNameAttribute, ok := attributes["group_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group_name is missing from object`)

		return nil, diags
	}

	groupNameVal, ok := groupNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group_name expected to be basetypes.StringValue, was: %T`, groupNameAttribute))
	}

	modifiedOnAttribute, ok := attributes["modified_on"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`modified_on is missing from object`)

		return nil, diags
	}

	modifiedOnVal, ok := modifiedOnAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`modified_on expected to be basetypes.StringValue, was: %T`, modifiedOnAttribute))
	}

	rolesAttribute, ok := attributes["roles"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`roles is missing from object`)

		return nil, diags
	}

	rolesVal, ok := rolesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`roles expected to be basetypes.ListValue, was: %T`, rolesAttribute))
	}

	usersAttribute, ok := attributes["users"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`users is missing from object`)

		return nil, diags
	}

	usersVal, ok := usersAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`users expected to be basetypes.ListValue, was: %T`, usersAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ResultValue{
		CreatedOn:  createdOnVal,
		ExternalId: externalIdVal,
		GroupId:    groupIdVal,
		GroupName:  groupNameVal,
		ModifiedOn: modifiedOnVal,
		Roles:      rolesVal,
		Users:      usersVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewResultValueNull() ResultValue {
	return ResultValue{
		state: attr.ValueStateNull,
	}
}

func NewResultValueUnknown() ResultValue {
	return ResultValue{
		state: attr.ValueStateUnknown,
	}
}

func NewResultValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ResultValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ResultValue Attribute Value",
				"While creating a ResultValue value, a missing attribute value was detected. "+
					"A ResultValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ResultValue Attribute Type",
				"While creating a ResultValue value, an invalid attribute value was detected. "+
					"A ResultValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ResultValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ResultValue Attribute Value",
				"While creating a ResultValue value, an extra attribute value was detected. "+
					"A ResultValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ResultValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	createdOnAttribute, ok := attributes["created_on"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_on is missing from object`)

		return NewResultValueUnknown(), diags
	}

	createdOnVal, ok := createdOnAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_on expected to be basetypes.StringValue, was: %T`, createdOnAttribute))
	}

	externalIdAttribute, ok := attributes["external_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`external_id is missing from object`)

		return NewResultValueUnknown(), diags
	}

	externalIdVal, ok := externalIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`external_id expected to be basetypes.StringValue, was: %T`, externalIdAttribute))
	}

	groupIdAttribute, ok := attributes["group_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group_id is missing from object`)

		return NewResultValueUnknown(), diags
	}

	groupIdVal, ok := groupIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group_id expected to be basetypes.StringValue, was: %T`, groupIdAttribute))
	}

	groupNameAttribute, ok := attributes["group_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group_name is missing from object`)

		return NewResultValueUnknown(), diags
	}

	groupNameVal, ok := groupNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group_name expected to be basetypes.StringValue, was: %T`, groupNameAttribute))
	}

	modifiedOnAttribute, ok := attributes["modified_on"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`modified_on is missing from object`)

		return NewResultValueUnknown(), diags
	}

	modifiedOnVal, ok := modifiedOnAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`modified_on expected to be basetypes.StringValue, was: %T`, modifiedOnAttribute))
	}

	rolesAttribute, ok := attributes["roles"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`roles is missing from object`)

		return NewResultValueUnknown(), diags
	}

	rolesVal, ok := rolesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`roles expected to be basetypes.ListValue, was: %T`, rolesAttribute))
	}

	usersAttribute, ok := attributes["users"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`users is missing from object`)

		return NewResultValueUnknown(), diags
	}

	usersVal, ok := usersAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`users expected to be basetypes.ListValue, was: %T`, usersAttribute))
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	return ResultValue{
		CreatedOn:  createdOnVal,
		ExternalId: externalIdVal,
		GroupId:    groupIdVal,
		GroupName:  groupNameVal,
		ModifiedOn: modifiedOnVal,
		Roles:      rolesVal,
		Users:      usersVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewResultValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ResultValue {
	object, diags := NewResultValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewResultValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ResultType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewResultValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewResultValueUnknown(), nil
	}

	if in.IsNull() {
		return NewResultValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewResultValueMust(ResultValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ResultType) ValueType(ctx context.Context) attr.Value {
	return ResultValue{}
}

var _ basetypes.ObjectValuable = ResultValue{}

type ResultValue struct {
	CreatedOn  basetypes.StringValue `tfsdk:"created_on"`
	ExternalId basetypes.StringValue `tfsdk:"external_id"`
	GroupId    basetypes.StringValue `tfsdk:"group_id"`
	GroupName  basetypes.StringValue `tfsdk:"group_name"`
	ModifiedOn basetypes.StringValue `tfsdk:"modified_on"`
	Roles      basetypes.ListValue   `tfsdk:"roles"`
	Users      basetypes.ListValue   `tfsdk:"users"`
	state      attr.ValueState
}

func (v ResultValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 7)

	var val tftypes.Value
	var err error

	attrTypes["created_on"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["external_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["group_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["group_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["modified_on"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["roles"] = basetypes.ListType{
		ElemType: RolesValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["users"] = basetypes.ListType{
		ElemType: UsersValue{}.Type(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 7)

		val, err = v.CreatedOn.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_on"] = val

		val, err = v.ExternalId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["external_id"] = val

		val, err = v.GroupId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["group_id"] = val

		val, err = v.GroupName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["group_name"] = val

		val, err = v.ModifiedOn.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["modified_on"] = val

		val, err = v.Roles.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["roles"] = val

		val, err = v.Users.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["users"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ResultValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ResultValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ResultValue) String() string {
	return "ResultValue"
}

func (v ResultValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	roles := types.ListValueMust(
		RolesType{
			basetypes.ObjectType{
				AttrTypes: RolesValue{}.AttributeTypes(ctx),
			},
		},
		v.Roles.Elements(),
	)

	if v.Roles.IsNull() {
		roles = types.ListNull(
			RolesType{
				basetypes.ObjectType{
					AttrTypes: RolesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Roles.IsUnknown() {
		roles = types.ListUnknown(
			RolesType{
				basetypes.ObjectType{
					AttrTypes: RolesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	users := types.ListValueMust(
		UsersType{
			basetypes.ObjectType{
				AttrTypes: UsersValue{}.AttributeTypes(ctx),
			},
		},
		v.Users.Elements(),
	)

	if v.Users.IsNull() {
		users = types.ListNull(
			UsersType{
				basetypes.ObjectType{
					AttrTypes: UsersValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Users.IsUnknown() {
		users = types.ListUnknown(
			UsersType{
				basetypes.ObjectType{
					AttrTypes: UsersValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	attributeTypes := map[string]attr.Type{
		"created_on":  basetypes.StringType{},
		"external_id": basetypes.StringType{},
		"group_id":    basetypes.StringType{},
		"group_name":  basetypes.StringType{},
		"modified_on": basetypes.StringType{},
		"roles": basetypes.ListType{
			ElemType: RolesValue{}.Type(ctx),
		},
		"users": basetypes.ListType{
			ElemType: UsersValue{}.Type(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created_on":  v.CreatedOn,
			"external_id": v.ExternalId,
			"group_id":    v.GroupId,
			"group_name":  v.GroupName,
			"modified_on": v.ModifiedOn,
			"roles":       roles,
			"users":       users,
		})

	return objVal, diags
}

func (v ResultValue) Equal(o attr.Value) bool {
	other, ok := o.(ResultValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedOn.Equal(other.CreatedOn) {
		return false
	}

	if !v.ExternalId.Equal(other.ExternalId) {
		return false
	}

	if !v.GroupId.Equal(other.GroupId) {
		return false
	}

	if !v.GroupName.Equal(other.GroupName) {
		return false
	}

	if !v.ModifiedOn.Equal(other.ModifiedOn) {
		return false
	}

	if !v.Roles.Equal(other.Roles) {
		return false
	}

	if !v.Users.Equal(other.Users) {
		return false
	}

	return true
}

func (v ResultValue) Type(ctx context.Context) attr.Type {
	return ResultType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ResultValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_on":  basetypes.StringType{},
		"external_id": basetypes.StringType{},
		"group_id":    basetypes.StringType{},
		"group_name":  basetypes.StringType{},
		"modified_on": basetypes.StringType{},
		"roles": basetypes.ListType{
			ElemType: RolesValue{}.Type(ctx),
		},
		"users": basetypes.ListType{
			ElemType: UsersValue{}.Type(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = RolesType{}

type RolesType struct {
	basetypes.ObjectType
}

func (t RolesType) Equal(o attr.Type) bool {
	other, ok := o.(RolesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RolesType) String() string {
	return "RolesType"
}

func (t RolesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	roleIdAttribute, ok := attributes["role_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_id is missing from object`)

		return nil, diags
	}

	roleIdVal, ok := roleIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_id expected to be basetypes.StringValue, was: %T`, roleIdAttribute))
	}

	roleNameAttribute, ok := attributes["role_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_name is missing from object`)

		return nil, diags
	}

	roleNameVal, ok := roleNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_name expected to be basetypes.StringValue, was: %T`, roleNameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RolesValue{
		RoleId:   roleIdVal,
		RoleName: roleNameVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewRolesValueNull() RolesValue {
	return RolesValue{
		state: attr.ValueStateNull,
	}
}

func NewRolesValueUnknown() RolesValue {
	return RolesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRolesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RolesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RolesValue Attribute Value",
				"While creating a RolesValue value, a missing attribute value was detected. "+
					"A RolesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RolesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RolesValue Attribute Type",
				"While creating a RolesValue value, an invalid attribute value was detected. "+
					"A RolesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RolesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RolesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RolesValue Attribute Value",
				"While creating a RolesValue value, an extra attribute value was detected. "+
					"A RolesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RolesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRolesValueUnknown(), diags
	}

	roleIdAttribute, ok := attributes["role_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_id is missing from object`)

		return NewRolesValueUnknown(), diags
	}

	roleIdVal, ok := roleIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_id expected to be basetypes.StringValue, was: %T`, roleIdAttribute))
	}

	roleNameAttribute, ok := attributes["role_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_name is missing from object`)

		return NewRolesValueUnknown(), diags
	}

	roleNameVal, ok := roleNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_name expected to be basetypes.StringValue, was: %T`, roleNameAttribute))
	}

	if diags.HasError() {
		return NewRolesValueUnknown(), diags
	}

	return RolesValue{
		RoleId:   roleIdVal,
		RoleName: roleNameVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewRolesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RolesValue {
	object, diags := NewRolesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRolesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RolesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRolesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRolesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRolesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRolesValueMust(RolesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RolesType) ValueType(ctx context.Context) attr.Value {
	return RolesValue{}
}

var _ basetypes.ObjectValuable = RolesValue{}

type RolesValue struct {
	RoleId   basetypes.StringValue `tfsdk:"role_id"`
	RoleName basetypes.StringValue `tfsdk:"role_name"`
	state    attr.ValueState
}

func (v RolesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["role_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["role_name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.RoleId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["role_id"] = val

		val, err = v.RoleName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["role_name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RolesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RolesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RolesValue) String() string {
	return "RolesValue"
}

func (v RolesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"role_id":   basetypes.StringType{},
		"role_name": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"role_id":   v.RoleId,
			"role_name": v.RoleName,
		})

	return objVal, diags
}

func (v RolesValue) Equal(o attr.Value) bool {
	other, ok := o.(RolesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.RoleId.Equal(other.RoleId) {
		return false
	}

	if !v.RoleName.Equal(other.RoleName) {
		return false
	}

	return true
}

func (v RolesValue) Type(ctx context.Context) attr.Type {
	return RolesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RolesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"role_id":   basetypes.StringType{},
		"role_name": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = UsersType{}

type UsersType struct {
	basetypes.ObjectType
}

func (t UsersType) Equal(o attr.Type) bool {
	other, ok := o.(UsersType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t UsersType) String() string {
	return "UsersType"
}

func (t UsersType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return nil, diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	userIdAttribute, ok := attributes["user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_id is missing from object`)

		return nil, diags
	}

	userIdVal, ok := userIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_id expected to be basetypes.StringValue, was: %T`, userIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return UsersValue{
		Email:  emailVal,
		UserId: userIdVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewUsersValueNull() UsersValue {
	return UsersValue{
		state: attr.ValueStateNull,
	}
}

func NewUsersValueUnknown() UsersValue {
	return UsersValue{
		state: attr.ValueStateUnknown,
	}
}

func NewUsersValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (UsersValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing UsersValue Attribute Value",
				"While creating a UsersValue value, a missing attribute value was detected. "+
					"A UsersValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UsersValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid UsersValue Attribute Type",
				"While creating a UsersValue value, an invalid attribute value was detected. "+
					"A UsersValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UsersValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("UsersValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra UsersValue Attribute Value",
				"While creating a UsersValue value, an extra attribute value was detected. "+
					"A UsersValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra UsersValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewUsersValueUnknown(), diags
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return NewUsersValueUnknown(), diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	userIdAttribute, ok := attributes["user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_id is missing from object`)

		return NewUsersValueUnknown(), diags
	}

	userIdVal, ok := userIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_id expected to be basetypes.StringValue, was: %T`, userIdAttribute))
	}

	if diags.HasError() {
		return NewUsersValueUnknown(), diags
	}

	return UsersValue{
		Email:  emailVal,
		UserId: userIdVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewUsersValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) UsersValue {
	object, diags := NewUsersValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewUsersValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t UsersType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewUsersValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewUsersValueUnknown(), nil
	}

	if in.IsNull() {
		return NewUsersValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewUsersValueMust(UsersValue{}.AttributeTypes(ctx), attributes), nil
}

func (t UsersType) ValueType(ctx context.Context) attr.Value {
	return UsersValue{}
}

var _ basetypes.ObjectValuable = UsersValue{}

type UsersValue struct {
	Email  basetypes.StringValue `tfsdk:"email"`
	UserId basetypes.StringValue `tfsdk:"user_id"`
	state  attr.ValueState
}

func (v UsersValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["user_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Email.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email"] = val

		val, err = v.UserId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["user_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v UsersValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v UsersValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v UsersValue) String() string {
	return "UsersValue"
}

func (v UsersValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"email":   basetypes.StringType{},
		"user_id": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"email":   v.Email,
			"user_id": v.UserId,
		})

	return objVal, diags
}

func (v UsersValue) Equal(o attr.Value) bool {
	other, ok := o.(UsersValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Email.Equal(other.Email) {
		return false
	}

	if !v.UserId.Equal(other.UserId) {
		return false
	}

	return true
}

func (v UsersValue) Type(ctx context.Context) attr.Type {
	return UsersType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v UsersValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"email":   basetypes.StringType{},
		"user_id": basetypes.StringType{},
	}
}
