// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_sql_job

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SqlJobDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cluster_id": schema.StringAttribute{
				Computed:            true,
				Description:         "ID of cluster in which SQL job gets executed",
				MarkdownDescription: "ID of cluster in which SQL job gets executed",
			},
			"cron_expression": schema.StringAttribute{
				Computed:            true,
				Description:         "Cron expression which determines SQL job execution interval",
				MarkdownDescription: "Cron expression which determines SQL job execution interval",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "SQL job description",
				MarkdownDescription: "SQL job description",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "SQL job name",
				MarkdownDescription: "SQL job name",
			},
			"next_execution": schema.StringAttribute{
				Computed:            true,
				Description:         "Timestamp of SQL job next execution (read only)",
				MarkdownDescription: "Timestamp of SQL job next execution (read only)",
			},
			"query": schema.StringAttribute{
				Computed:            true,
				Description:         "SQL query to execute",
				MarkdownDescription: "SQL query to execute",
			},
			"role_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Role used when SQL job is executed",
				MarkdownDescription: "Role used when SQL job is executed",
			},
			"sql_job_id": schema.StringAttribute{
				Required:            true,
				Description:         "SQL query scheduled job",
				MarkdownDescription: "SQL query scheduled job",
			},
			"timezone": schema.StringAttribute{
				Computed:            true,
				Description:         "Timezone in which CRON is evaluated. Defaults to UTC",
				MarkdownDescription: "Timezone in which CRON is evaluated. Defaults to UTC",
			},
		},
	}
}

type SqlJobModel struct {
	ClusterId      types.String `tfsdk:"cluster_id"`
	CronExpression types.String `tfsdk:"cron_expression"`
	Description    types.String `tfsdk:"description"`
	Name           types.String `tfsdk:"name"`
	NextExecution  types.String `tfsdk:"next_execution"`
	Query          types.String `tfsdk:"query"`
	RoleId         types.String `tfsdk:"role_id"`
	SqlJobId       types.String `tfsdk:"sql_job_id"`
	Timezone       types.String `tfsdk:"timezone"`
}
