// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_roles

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func RolesDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"result": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"all_roles": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"admin_option": schema.BoolAttribute{
										Computed:            true,
										Description:         "Admin option",
										MarkdownDescription: "Admin option",
									},
									"principal": schema.SingleNestedAttribute{
										Attributes: map[string]schema.Attribute{
											"id": schema.StringAttribute{
												Computed:            true,
												Description:         "Principal ID",
												MarkdownDescription: "Principal ID",
											},
											"type": schema.StringAttribute{
												Computed:            true,
												Description:         "Principal type",
												MarkdownDescription: "Principal type",
											},
										},
										CustomType: PrincipalType{
											ObjectType: types.ObjectType{
												AttrTypes: PrincipalValue{}.AttributeTypes(ctx),
											},
										},
										Computed:            true,
										Description:         "Principal (read only)",
										MarkdownDescription: "Principal (read only)",
									},
									"role_id": schema.StringAttribute{
										Computed:            true,
										Description:         "Role ID",
										MarkdownDescription: "Role ID",
									},
									"role_name": schema.StringAttribute{
										Computed:            true,
										Description:         "Role name",
										MarkdownDescription: "Role name",
									},
								},
								CustomType: AllRolesType{
									ObjectType: types.ObjectType{
										AttrTypes: AllRolesValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed:            true,
							Description:         "All directly granted and inherited roles (read only)",
							MarkdownDescription: "All directly granted and inherited roles (read only)",
						},
						"created_on": schema.StringAttribute{
							Computed:            true,
							Description:         "Creation date (read only)",
							MarkdownDescription: "Creation date (read only)",
						},
						"directly_granted_roles": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"admin_option": schema.BoolAttribute{
										Computed:            true,
										Description:         "Admin option",
										MarkdownDescription: "Admin option",
									},
									"principal": schema.SingleNestedAttribute{
										Attributes: map[string]schema.Attribute{
											"id": schema.StringAttribute{
												Computed:            true,
												Description:         "Principal ID",
												MarkdownDescription: "Principal ID",
											},
											"type": schema.StringAttribute{
												Computed:            true,
												Description:         "Principal type",
												MarkdownDescription: "Principal type",
											},
										},
										CustomType: PrincipalType{
											ObjectType: types.ObjectType{
												AttrTypes: PrincipalValue{}.AttributeTypes(ctx),
											},
										},
										Computed:            true,
										Description:         "Principal (read only)",
										MarkdownDescription: "Principal (read only)",
									},
									"role_id": schema.StringAttribute{
										Computed:            true,
										Description:         "Role ID",
										MarkdownDescription: "Role ID",
									},
									"role_name": schema.StringAttribute{
										Computed:            true,
										Description:         "Role name",
										MarkdownDescription: "Role name",
									},
								},
								CustomType: DirectlyGrantedRolesType{
									ObjectType: types.ObjectType{
										AttrTypes: DirectlyGrantedRolesValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed:            true,
							Description:         "Directly granted roles (read only)",
							MarkdownDescription: "Directly granted roles (read only)",
						},
						"modified_on": schema.StringAttribute{
							Computed:            true,
							Description:         "Modified date (read only)",
							MarkdownDescription: "Modified date (read only)",
						},
						"owning_role_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Owning role (read only)",
							MarkdownDescription: "Owning role (read only)",
						},
						"role_description": schema.StringAttribute{
							Computed:            true,
							Description:         "Role description (read only)",
							MarkdownDescription: "Role description (read only)",
						},
						"role_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Role ID (read only)",
							MarkdownDescription: "Role ID (read only)",
						},
						"role_name": schema.StringAttribute{
							Computed:            true,
							Description:         "Role name (read only)",
							MarkdownDescription: "Role name (read only)",
						},
					},
					CustomType: ResultType{
						ObjectType: types.ObjectType{
							AttrTypes: ResultValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "A page of results.",
				MarkdownDescription: "A page of results.",
			},
		},
	}
}

type RolesModel struct {
	Result types.List `tfsdk:"result"`
}

var _ basetypes.ObjectTypable = ResultType{}

type ResultType struct {
	basetypes.ObjectType
}

func (t ResultType) Equal(o attr.Type) bool {
	other, ok := o.(ResultType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ResultType) String() string {
	return "ResultType"
}

func (t ResultType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	allRolesAttribute, ok := attributes["all_roles"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`all_roles is missing from object`)

		return nil, diags
	}

	allRolesVal, ok := allRolesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`all_roles expected to be basetypes.ListValue, was: %T`, allRolesAttribute))
	}

	createdOnAttribute, ok := attributes["created_on"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_on is missing from object`)

		return nil, diags
	}

	createdOnVal, ok := createdOnAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_on expected to be basetypes.StringValue, was: %T`, createdOnAttribute))
	}

	directlyGrantedRolesAttribute, ok := attributes["directly_granted_roles"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`directly_granted_roles is missing from object`)

		return nil, diags
	}

	directlyGrantedRolesVal, ok := directlyGrantedRolesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`directly_granted_roles expected to be basetypes.ListValue, was: %T`, directlyGrantedRolesAttribute))
	}

	modifiedOnAttribute, ok := attributes["modified_on"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`modified_on is missing from object`)

		return nil, diags
	}

	modifiedOnVal, ok := modifiedOnAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`modified_on expected to be basetypes.StringValue, was: %T`, modifiedOnAttribute))
	}

	owningRoleIdAttribute, ok := attributes["owning_role_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`owning_role_id is missing from object`)

		return nil, diags
	}

	owningRoleIdVal, ok := owningRoleIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`owning_role_id expected to be basetypes.StringValue, was: %T`, owningRoleIdAttribute))
	}

	roleDescriptionAttribute, ok := attributes["role_description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_description is missing from object`)

		return nil, diags
	}

	roleDescriptionVal, ok := roleDescriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_description expected to be basetypes.StringValue, was: %T`, roleDescriptionAttribute))
	}

	roleIdAttribute, ok := attributes["role_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_id is missing from object`)

		return nil, diags
	}

	roleIdVal, ok := roleIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_id expected to be basetypes.StringValue, was: %T`, roleIdAttribute))
	}

	roleNameAttribute, ok := attributes["role_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_name is missing from object`)

		return nil, diags
	}

	roleNameVal, ok := roleNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_name expected to be basetypes.StringValue, was: %T`, roleNameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ResultValue{
		AllRoles:             allRolesVal,
		CreatedOn:            createdOnVal,
		DirectlyGrantedRoles: directlyGrantedRolesVal,
		ModifiedOn:           modifiedOnVal,
		OwningRoleId:         owningRoleIdVal,
		RoleDescription:      roleDescriptionVal,
		RoleId:               roleIdVal,
		RoleName:             roleNameVal,
		state:                attr.ValueStateKnown,
	}, diags
}

func NewResultValueNull() ResultValue {
	return ResultValue{
		state: attr.ValueStateNull,
	}
}

func NewResultValueUnknown() ResultValue {
	return ResultValue{
		state: attr.ValueStateUnknown,
	}
}

func NewResultValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ResultValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ResultValue Attribute Value",
				"While creating a ResultValue value, a missing attribute value was detected. "+
					"A ResultValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ResultValue Attribute Type",
				"While creating a ResultValue value, an invalid attribute value was detected. "+
					"A ResultValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ResultValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ResultValue Attribute Value",
				"While creating a ResultValue value, an extra attribute value was detected. "+
					"A ResultValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ResultValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	allRolesAttribute, ok := attributes["all_roles"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`all_roles is missing from object`)

		return NewResultValueUnknown(), diags
	}

	allRolesVal, ok := allRolesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`all_roles expected to be basetypes.ListValue, was: %T`, allRolesAttribute))
	}

	createdOnAttribute, ok := attributes["created_on"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_on is missing from object`)

		return NewResultValueUnknown(), diags
	}

	createdOnVal, ok := createdOnAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_on expected to be basetypes.StringValue, was: %T`, createdOnAttribute))
	}

	directlyGrantedRolesAttribute, ok := attributes["directly_granted_roles"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`directly_granted_roles is missing from object`)

		return NewResultValueUnknown(), diags
	}

	directlyGrantedRolesVal, ok := directlyGrantedRolesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`directly_granted_roles expected to be basetypes.ListValue, was: %T`, directlyGrantedRolesAttribute))
	}

	modifiedOnAttribute, ok := attributes["modified_on"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`modified_on is missing from object`)

		return NewResultValueUnknown(), diags
	}

	modifiedOnVal, ok := modifiedOnAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`modified_on expected to be basetypes.StringValue, was: %T`, modifiedOnAttribute))
	}

	owningRoleIdAttribute, ok := attributes["owning_role_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`owning_role_id is missing from object`)

		return NewResultValueUnknown(), diags
	}

	owningRoleIdVal, ok := owningRoleIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`owning_role_id expected to be basetypes.StringValue, was: %T`, owningRoleIdAttribute))
	}

	roleDescriptionAttribute, ok := attributes["role_description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_description is missing from object`)

		return NewResultValueUnknown(), diags
	}

	roleDescriptionVal, ok := roleDescriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_description expected to be basetypes.StringValue, was: %T`, roleDescriptionAttribute))
	}

	roleIdAttribute, ok := attributes["role_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_id is missing from object`)

		return NewResultValueUnknown(), diags
	}

	roleIdVal, ok := roleIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_id expected to be basetypes.StringValue, was: %T`, roleIdAttribute))
	}

	roleNameAttribute, ok := attributes["role_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_name is missing from object`)

		return NewResultValueUnknown(), diags
	}

	roleNameVal, ok := roleNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_name expected to be basetypes.StringValue, was: %T`, roleNameAttribute))
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	return ResultValue{
		AllRoles:             allRolesVal,
		CreatedOn:            createdOnVal,
		DirectlyGrantedRoles: directlyGrantedRolesVal,
		ModifiedOn:           modifiedOnVal,
		OwningRoleId:         owningRoleIdVal,
		RoleDescription:      roleDescriptionVal,
		RoleId:               roleIdVal,
		RoleName:             roleNameVal,
		state:                attr.ValueStateKnown,
	}, diags
}

func NewResultValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ResultValue {
	object, diags := NewResultValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewResultValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ResultType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewResultValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewResultValueUnknown(), nil
	}

	if in.IsNull() {
		return NewResultValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewResultValueMust(ResultValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ResultType) ValueType(ctx context.Context) attr.Value {
	return ResultValue{}
}

var _ basetypes.ObjectValuable = ResultValue{}

type ResultValue struct {
	AllRoles             basetypes.ListValue   `tfsdk:"all_roles"`
	CreatedOn            basetypes.StringValue `tfsdk:"created_on"`
	DirectlyGrantedRoles basetypes.ListValue   `tfsdk:"directly_granted_roles"`
	ModifiedOn           basetypes.StringValue `tfsdk:"modified_on"`
	OwningRoleId         basetypes.StringValue `tfsdk:"owning_role_id"`
	RoleDescription      basetypes.StringValue `tfsdk:"role_description"`
	RoleId               basetypes.StringValue `tfsdk:"role_id"`
	RoleName             basetypes.StringValue `tfsdk:"role_name"`
	state                attr.ValueState
}

func (v ResultValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 8)

	var val tftypes.Value
	var err error

	attrTypes["all_roles"] = basetypes.ListType{
		ElemType: AllRolesValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["created_on"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["directly_granted_roles"] = basetypes.ListType{
		ElemType: DirectlyGrantedRolesValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["modified_on"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["owning_role_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["role_description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["role_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["role_name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 8)

		val, err = v.AllRoles.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["all_roles"] = val

		val, err = v.CreatedOn.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_on"] = val

		val, err = v.DirectlyGrantedRoles.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["directly_granted_roles"] = val

		val, err = v.ModifiedOn.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["modified_on"] = val

		val, err = v.OwningRoleId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["owning_role_id"] = val

		val, err = v.RoleDescription.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["role_description"] = val

		val, err = v.RoleId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["role_id"] = val

		val, err = v.RoleName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["role_name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ResultValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ResultValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ResultValue) String() string {
	return "ResultValue"
}

func (v ResultValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	allRoles := types.ListValueMust(
		AllRolesType{
			basetypes.ObjectType{
				AttrTypes: AllRolesValue{}.AttributeTypes(ctx),
			},
		},
		v.AllRoles.Elements(),
	)

	if v.AllRoles.IsNull() {
		allRoles = types.ListNull(
			AllRolesType{
				basetypes.ObjectType{
					AttrTypes: AllRolesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.AllRoles.IsUnknown() {
		allRoles = types.ListUnknown(
			AllRolesType{
				basetypes.ObjectType{
					AttrTypes: AllRolesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	directlyGrantedRoles := types.ListValueMust(
		DirectlyGrantedRolesType{
			basetypes.ObjectType{
				AttrTypes: DirectlyGrantedRolesValue{}.AttributeTypes(ctx),
			},
		},
		v.DirectlyGrantedRoles.Elements(),
	)

	if v.DirectlyGrantedRoles.IsNull() {
		directlyGrantedRoles = types.ListNull(
			DirectlyGrantedRolesType{
				basetypes.ObjectType{
					AttrTypes: DirectlyGrantedRolesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.DirectlyGrantedRoles.IsUnknown() {
		directlyGrantedRoles = types.ListUnknown(
			DirectlyGrantedRolesType{
				basetypes.ObjectType{
					AttrTypes: DirectlyGrantedRolesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	attributeTypes := map[string]attr.Type{
		"all_roles": basetypes.ListType{
			ElemType: AllRolesValue{}.Type(ctx),
		},
		"created_on": basetypes.StringType{},
		"directly_granted_roles": basetypes.ListType{
			ElemType: DirectlyGrantedRolesValue{}.Type(ctx),
		},
		"modified_on":      basetypes.StringType{},
		"owning_role_id":   basetypes.StringType{},
		"role_description": basetypes.StringType{},
		"role_id":          basetypes.StringType{},
		"role_name":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"all_roles":              allRoles,
			"created_on":             v.CreatedOn,
			"directly_granted_roles": directlyGrantedRoles,
			"modified_on":            v.ModifiedOn,
			"owning_role_id":         v.OwningRoleId,
			"role_description":       v.RoleDescription,
			"role_id":                v.RoleId,
			"role_name":              v.RoleName,
		})

	return objVal, diags
}

func (v ResultValue) Equal(o attr.Value) bool {
	other, ok := o.(ResultValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AllRoles.Equal(other.AllRoles) {
		return false
	}

	if !v.CreatedOn.Equal(other.CreatedOn) {
		return false
	}

	if !v.DirectlyGrantedRoles.Equal(other.DirectlyGrantedRoles) {
		return false
	}

	if !v.ModifiedOn.Equal(other.ModifiedOn) {
		return false
	}

	if !v.OwningRoleId.Equal(other.OwningRoleId) {
		return false
	}

	if !v.RoleDescription.Equal(other.RoleDescription) {
		return false
	}

	if !v.RoleId.Equal(other.RoleId) {
		return false
	}

	if !v.RoleName.Equal(other.RoleName) {
		return false
	}

	return true
}

func (v ResultValue) Type(ctx context.Context) attr.Type {
	return ResultType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ResultValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"all_roles": basetypes.ListType{
			ElemType: AllRolesValue{}.Type(ctx),
		},
		"created_on": basetypes.StringType{},
		"directly_granted_roles": basetypes.ListType{
			ElemType: DirectlyGrantedRolesValue{}.Type(ctx),
		},
		"modified_on":      basetypes.StringType{},
		"owning_role_id":   basetypes.StringType{},
		"role_description": basetypes.StringType{},
		"role_id":          basetypes.StringType{},
		"role_name":        basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = AllRolesType{}

type AllRolesType struct {
	basetypes.ObjectType
}

func (t AllRolesType) Equal(o attr.Type) bool {
	other, ok := o.(AllRolesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AllRolesType) String() string {
	return "AllRolesType"
}

func (t AllRolesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	adminOptionAttribute, ok := attributes["admin_option"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`admin_option is missing from object`)

		return nil, diags
	}

	adminOptionVal, ok := adminOptionAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`admin_option expected to be basetypes.BoolValue, was: %T`, adminOptionAttribute))
	}

	principalAttribute, ok := attributes["principal"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`principal is missing from object`)

		return nil, diags
	}

	principalVal, ok := principalAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`principal expected to be basetypes.ObjectValue, was: %T`, principalAttribute))
	}

	roleIdAttribute, ok := attributes["role_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_id is missing from object`)

		return nil, diags
	}

	roleIdVal, ok := roleIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_id expected to be basetypes.StringValue, was: %T`, roleIdAttribute))
	}

	roleNameAttribute, ok := attributes["role_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_name is missing from object`)

		return nil, diags
	}

	roleNameVal, ok := roleNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_name expected to be basetypes.StringValue, was: %T`, roleNameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AllRolesValue{
		AdminOption: adminOptionVal,
		Principal:   principalVal,
		RoleId:      roleIdVal,
		RoleName:    roleNameVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewAllRolesValueNull() AllRolesValue {
	return AllRolesValue{
		state: attr.ValueStateNull,
	}
}

func NewAllRolesValueUnknown() AllRolesValue {
	return AllRolesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAllRolesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AllRolesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AllRolesValue Attribute Value",
				"While creating a AllRolesValue value, a missing attribute value was detected. "+
					"A AllRolesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AllRolesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AllRolesValue Attribute Type",
				"While creating a AllRolesValue value, an invalid attribute value was detected. "+
					"A AllRolesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AllRolesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AllRolesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AllRolesValue Attribute Value",
				"While creating a AllRolesValue value, an extra attribute value was detected. "+
					"A AllRolesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AllRolesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAllRolesValueUnknown(), diags
	}

	adminOptionAttribute, ok := attributes["admin_option"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`admin_option is missing from object`)

		return NewAllRolesValueUnknown(), diags
	}

	adminOptionVal, ok := adminOptionAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`admin_option expected to be basetypes.BoolValue, was: %T`, adminOptionAttribute))
	}

	principalAttribute, ok := attributes["principal"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`principal is missing from object`)

		return NewAllRolesValueUnknown(), diags
	}

	principalVal, ok := principalAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`principal expected to be basetypes.ObjectValue, was: %T`, principalAttribute))
	}

	roleIdAttribute, ok := attributes["role_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_id is missing from object`)

		return NewAllRolesValueUnknown(), diags
	}

	roleIdVal, ok := roleIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_id expected to be basetypes.StringValue, was: %T`, roleIdAttribute))
	}

	roleNameAttribute, ok := attributes["role_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_name is missing from object`)

		return NewAllRolesValueUnknown(), diags
	}

	roleNameVal, ok := roleNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_name expected to be basetypes.StringValue, was: %T`, roleNameAttribute))
	}

	if diags.HasError() {
		return NewAllRolesValueUnknown(), diags
	}

	return AllRolesValue{
		AdminOption: adminOptionVal,
		Principal:   principalVal,
		RoleId:      roleIdVal,
		RoleName:    roleNameVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewAllRolesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AllRolesValue {
	object, diags := NewAllRolesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAllRolesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AllRolesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAllRolesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAllRolesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAllRolesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAllRolesValueMust(AllRolesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AllRolesType) ValueType(ctx context.Context) attr.Value {
	return AllRolesValue{}
}

var _ basetypes.ObjectValuable = AllRolesValue{}

type AllRolesValue struct {
	AdminOption basetypes.BoolValue   `tfsdk:"admin_option"`
	Principal   basetypes.ObjectValue `tfsdk:"principal"`
	RoleId      basetypes.StringValue `tfsdk:"role_id"`
	RoleName    basetypes.StringValue `tfsdk:"role_name"`
	state       attr.ValueState
}

func (v AllRolesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["admin_option"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["principal"] = basetypes.ObjectType{
		AttrTypes: PrincipalValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["role_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["role_name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.AdminOption.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["admin_option"] = val

		val, err = v.Principal.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["principal"] = val

		val, err = v.RoleId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["role_id"] = val

		val, err = v.RoleName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["role_name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AllRolesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AllRolesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AllRolesValue) String() string {
	return "AllRolesValue"
}

func (v AllRolesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var principal basetypes.ObjectValue

	if v.Principal.IsNull() {
		principal = types.ObjectNull(
			PrincipalValue{}.AttributeTypes(ctx),
		)
	}

	if v.Principal.IsUnknown() {
		principal = types.ObjectUnknown(
			PrincipalValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Principal.IsNull() && !v.Principal.IsUnknown() {
		principal = types.ObjectValueMust(
			PrincipalValue{}.AttributeTypes(ctx),
			v.Principal.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"admin_option": basetypes.BoolType{},
		"principal": basetypes.ObjectType{
			AttrTypes: PrincipalValue{}.AttributeTypes(ctx),
		},
		"role_id":   basetypes.StringType{},
		"role_name": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"admin_option": v.AdminOption,
			"principal":    principal,
			"role_id":      v.RoleId,
			"role_name":    v.RoleName,
		})

	return objVal, diags
}

func (v AllRolesValue) Equal(o attr.Value) bool {
	other, ok := o.(AllRolesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AdminOption.Equal(other.AdminOption) {
		return false
	}

	if !v.Principal.Equal(other.Principal) {
		return false
	}

	if !v.RoleId.Equal(other.RoleId) {
		return false
	}

	if !v.RoleName.Equal(other.RoleName) {
		return false
	}

	return true
}

func (v AllRolesValue) Type(ctx context.Context) attr.Type {
	return AllRolesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AllRolesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"admin_option": basetypes.BoolType{},
		"principal": basetypes.ObjectType{
			AttrTypes: PrincipalValue{}.AttributeTypes(ctx),
		},
		"role_id":   basetypes.StringType{},
		"role_name": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = PrincipalType{}

type PrincipalType struct {
	basetypes.ObjectType
}

func (t PrincipalType) Equal(o attr.Type) bool {
	other, ok := o.(PrincipalType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PrincipalType) String() string {
	return "PrincipalType"
}

func (t PrincipalType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PrincipalValue{
		Id:            idVal,
		PrincipalType: typeVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewPrincipalValueNull() PrincipalValue {
	return PrincipalValue{
		state: attr.ValueStateNull,
	}
}

func NewPrincipalValueUnknown() PrincipalValue {
	return PrincipalValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPrincipalValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PrincipalValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PrincipalValue Attribute Value",
				"While creating a PrincipalValue value, a missing attribute value was detected. "+
					"A PrincipalValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PrincipalValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PrincipalValue Attribute Type",
				"While creating a PrincipalValue value, an invalid attribute value was detected. "+
					"A PrincipalValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PrincipalValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PrincipalValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PrincipalValue Attribute Value",
				"While creating a PrincipalValue value, an extra attribute value was detected. "+
					"A PrincipalValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PrincipalValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPrincipalValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewPrincipalValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewPrincipalValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewPrincipalValueUnknown(), diags
	}

	return PrincipalValue{
		Id:            idVal,
		PrincipalType: typeVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewPrincipalValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PrincipalValue {
	object, diags := NewPrincipalValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPrincipalValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PrincipalType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPrincipalValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPrincipalValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPrincipalValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPrincipalValueMust(PrincipalValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PrincipalType) ValueType(ctx context.Context) attr.Value {
	return PrincipalValue{}
}

var _ basetypes.ObjectValuable = PrincipalValue{}

type PrincipalValue struct {
	Id            basetypes.StringValue `tfsdk:"id"`
	PrincipalType basetypes.StringValue `tfsdk:"type"`
	state         attr.ValueState
}

func (v PrincipalValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.PrincipalType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PrincipalValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PrincipalValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PrincipalValue) String() string {
	return "PrincipalValue"
}

func (v PrincipalValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"type": v.PrincipalType,
		})

	return objVal, diags
}

func (v PrincipalValue) Equal(o attr.Value) bool {
	other, ok := o.(PrincipalValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.PrincipalType.Equal(other.PrincipalType) {
		return false
	}

	return true
}

func (v PrincipalValue) Type(ctx context.Context) attr.Type {
	return PrincipalType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PrincipalValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = DirectlyGrantedRolesType{}

type DirectlyGrantedRolesType struct {
	basetypes.ObjectType
}

func (t DirectlyGrantedRolesType) Equal(o attr.Type) bool {
	other, ok := o.(DirectlyGrantedRolesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DirectlyGrantedRolesType) String() string {
	return "DirectlyGrantedRolesType"
}

func (t DirectlyGrantedRolesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	adminOptionAttribute, ok := attributes["admin_option"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`admin_option is missing from object`)

		return nil, diags
	}

	adminOptionVal, ok := adminOptionAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`admin_option expected to be basetypes.BoolValue, was: %T`, adminOptionAttribute))
	}

	principalAttribute, ok := attributes["principal"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`principal is missing from object`)

		return nil, diags
	}

	principalVal, ok := principalAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`principal expected to be basetypes.ObjectValue, was: %T`, principalAttribute))
	}

	roleIdAttribute, ok := attributes["role_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_id is missing from object`)

		return nil, diags
	}

	roleIdVal, ok := roleIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_id expected to be basetypes.StringValue, was: %T`, roleIdAttribute))
	}

	roleNameAttribute, ok := attributes["role_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_name is missing from object`)

		return nil, diags
	}

	roleNameVal, ok := roleNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_name expected to be basetypes.StringValue, was: %T`, roleNameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DirectlyGrantedRolesValue{
		AdminOption: adminOptionVal,
		Principal:   principalVal,
		RoleId:      roleIdVal,
		RoleName:    roleNameVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewDirectlyGrantedRolesValueNull() DirectlyGrantedRolesValue {
	return DirectlyGrantedRolesValue{
		state: attr.ValueStateNull,
	}
}

func NewDirectlyGrantedRolesValueUnknown() DirectlyGrantedRolesValue {
	return DirectlyGrantedRolesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDirectlyGrantedRolesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DirectlyGrantedRolesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DirectlyGrantedRolesValue Attribute Value",
				"While creating a DirectlyGrantedRolesValue value, a missing attribute value was detected. "+
					"A DirectlyGrantedRolesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DirectlyGrantedRolesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DirectlyGrantedRolesValue Attribute Type",
				"While creating a DirectlyGrantedRolesValue value, an invalid attribute value was detected. "+
					"A DirectlyGrantedRolesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DirectlyGrantedRolesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DirectlyGrantedRolesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DirectlyGrantedRolesValue Attribute Value",
				"While creating a DirectlyGrantedRolesValue value, an extra attribute value was detected. "+
					"A DirectlyGrantedRolesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DirectlyGrantedRolesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDirectlyGrantedRolesValueUnknown(), diags
	}

	adminOptionAttribute, ok := attributes["admin_option"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`admin_option is missing from object`)

		return NewDirectlyGrantedRolesValueUnknown(), diags
	}

	adminOptionVal, ok := adminOptionAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`admin_option expected to be basetypes.BoolValue, was: %T`, adminOptionAttribute))
	}

	principalAttribute, ok := attributes["principal"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`principal is missing from object`)

		return NewDirectlyGrantedRolesValueUnknown(), diags
	}

	principalVal, ok := principalAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`principal expected to be basetypes.ObjectValue, was: %T`, principalAttribute))
	}

	roleIdAttribute, ok := attributes["role_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_id is missing from object`)

		return NewDirectlyGrantedRolesValueUnknown(), diags
	}

	roleIdVal, ok := roleIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_id expected to be basetypes.StringValue, was: %T`, roleIdAttribute))
	}

	roleNameAttribute, ok := attributes["role_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role_name is missing from object`)

		return NewDirectlyGrantedRolesValueUnknown(), diags
	}

	roleNameVal, ok := roleNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role_name expected to be basetypes.StringValue, was: %T`, roleNameAttribute))
	}

	if diags.HasError() {
		return NewDirectlyGrantedRolesValueUnknown(), diags
	}

	return DirectlyGrantedRolesValue{
		AdminOption: adminOptionVal,
		Principal:   principalVal,
		RoleId:      roleIdVal,
		RoleName:    roleNameVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewDirectlyGrantedRolesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DirectlyGrantedRolesValue {
	object, diags := NewDirectlyGrantedRolesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDirectlyGrantedRolesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DirectlyGrantedRolesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDirectlyGrantedRolesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDirectlyGrantedRolesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDirectlyGrantedRolesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDirectlyGrantedRolesValueMust(DirectlyGrantedRolesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DirectlyGrantedRolesType) ValueType(ctx context.Context) attr.Value {
	return DirectlyGrantedRolesValue{}
}

var _ basetypes.ObjectValuable = DirectlyGrantedRolesValue{}

type DirectlyGrantedRolesValue struct {
	AdminOption basetypes.BoolValue   `tfsdk:"admin_option"`
	Principal   basetypes.ObjectValue `tfsdk:"principal"`
	RoleId      basetypes.StringValue `tfsdk:"role_id"`
	RoleName    basetypes.StringValue `tfsdk:"role_name"`
	state       attr.ValueState
}

func (v DirectlyGrantedRolesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["admin_option"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["principal"] = basetypes.ObjectType{
		AttrTypes: PrincipalValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["role_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["role_name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.AdminOption.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["admin_option"] = val

		val, err = v.Principal.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["principal"] = val

		val, err = v.RoleId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["role_id"] = val

		val, err = v.RoleName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["role_name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DirectlyGrantedRolesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DirectlyGrantedRolesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DirectlyGrantedRolesValue) String() string {
	return "DirectlyGrantedRolesValue"
}

func (v DirectlyGrantedRolesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var principal basetypes.ObjectValue

	if v.Principal.IsNull() {
		principal = types.ObjectNull(
			PrincipalValue{}.AttributeTypes(ctx),
		)
	}

	if v.Principal.IsUnknown() {
		principal = types.ObjectUnknown(
			PrincipalValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Principal.IsNull() && !v.Principal.IsUnknown() {
		principal = types.ObjectValueMust(
			PrincipalValue{}.AttributeTypes(ctx),
			v.Principal.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"admin_option": basetypes.BoolType{},
		"principal": basetypes.ObjectType{
			AttrTypes: PrincipalValue{}.AttributeTypes(ctx),
		},
		"role_id":   basetypes.StringType{},
		"role_name": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"admin_option": v.AdminOption,
			"principal":    principal,
			"role_id":      v.RoleId,
			"role_name":    v.RoleName,
		})

	return objVal, diags
}

func (v DirectlyGrantedRolesValue) Equal(o attr.Value) bool {
	other, ok := o.(DirectlyGrantedRolesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AdminOption.Equal(other.AdminOption) {
		return false
	}

	if !v.Principal.Equal(other.Principal) {
		return false
	}

	if !v.RoleId.Equal(other.RoleId) {
		return false
	}

	if !v.RoleName.Equal(other.RoleName) {
		return false
	}

	return true
}

func (v DirectlyGrantedRolesValue) Type(ctx context.Context) attr.Type {
	return DirectlyGrantedRolesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DirectlyGrantedRolesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"admin_option": basetypes.BoolType{},
		"principal": basetypes.ObjectType{
			AttrTypes: PrincipalValue{}.AttributeTypes(ctx),
		},
		"role_id":   basetypes.StringType{},
		"role_name": basetypes.StringType{},
	}
}
