// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_data_quality_schedule

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func DataQualityScheduleDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"catalog_id": schema.StringAttribute{
				Required:            true,
				Description:         "- A catalog\n- This parameter can be looked up using `name` instead of its Id. Use `name=value` instead of an Id to lookup/search using the `value`. `value` must be encoded ([see RFC](https://www.rfc-editor.org/rfc/rfc3986#section-2.2) including `=`)\n",
				MarkdownDescription: "- A catalog\n- This parameter can be looked up using `name` instead of its Id. Use `name=value` instead of an Id to lookup/search using the `value`. `value` must be encoded ([see RFC](https://www.rfc-editor.org/rfc/rfc3986#section-2.2) including `=`)\n",
			},
			"cluster_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Cluster in which checks are executed",
				MarkdownDescription: "Cluster in which checks are executed",
			},
			"cron_expression": schema.StringAttribute{
				Computed:            true,
				Description:         "Cron expression which determines execution interval",
				MarkdownDescription: "Cron expression which determines execution interval",
			},
			"data_quality_checks": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"data_quality_check_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Data Quality check ID (read only)",
							MarkdownDescription: "Data Quality check ID (read only)",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "Data Quality check name",
							MarkdownDescription: "Data Quality check name",
						},
					},
					CustomType: DataQualityChecksType{
						ObjectType: types.ObjectType{
							AttrTypes: DataQualityChecksValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "List of data quality checks (read only)",
				MarkdownDescription: "List of data quality checks (read only)",
			},
			"data_quality_schedule_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Data Quality Schedule ID (read only)",
				MarkdownDescription: "Data Quality Schedule ID (read only)",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Is schedule enabled",
				MarkdownDescription: "Is schedule enabled",
			},
			"next_execution": schema.StringAttribute{
				Computed:            true,
				Description:         "Date and time of the next scheduled execution",
				MarkdownDescription: "Date and time of the next scheduled execution",
			},
			"role_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Role used when checks are executed",
				MarkdownDescription: "Role used when checks are executed",
			},
			"schema_id": schema.StringAttribute{
				Required:            true,
				Description:         "A schema from a catalog",
				MarkdownDescription: "A schema from a catalog",
			},
			"table_id": schema.StringAttribute{
				Required:            true,
				Description:         "A table from a catalog",
				MarkdownDescription: "A table from a catalog",
			},
			"timezone": schema.StringAttribute{
				Computed:            true,
				Description:         "Timezone in which CRON is evaluated",
				MarkdownDescription: "Timezone in which CRON is evaluated",
			},
		},
	}
}

type DataQualityScheduleModel struct {
	CatalogId             types.String `tfsdk:"catalog_id"`
	ClusterId             types.String `tfsdk:"cluster_id"`
	CronExpression        types.String `tfsdk:"cron_expression"`
	DataQualityChecks     types.List   `tfsdk:"data_quality_checks"`
	DataQualityScheduleId types.String `tfsdk:"data_quality_schedule_id"`
	Enabled               types.Bool   `tfsdk:"enabled"`
	NextExecution         types.String `tfsdk:"next_execution"`
	RoleId                types.String `tfsdk:"role_id"`
	SchemaId              types.String `tfsdk:"schema_id"`
	TableId               types.String `tfsdk:"table_id"`
	Timezone              types.String `tfsdk:"timezone"`
}

var _ basetypes.ObjectTypable = DataQualityChecksType{}

type DataQualityChecksType struct {
	basetypes.ObjectType
}

func (t DataQualityChecksType) Equal(o attr.Type) bool {
	other, ok := o.(DataQualityChecksType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DataQualityChecksType) String() string {
	return "DataQualityChecksType"
}

func (t DataQualityChecksType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	dataQualityCheckIdAttribute, ok := attributes["data_quality_check_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`data_quality_check_id is missing from object`)

		return nil, diags
	}

	dataQualityCheckIdVal, ok := dataQualityCheckIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`data_quality_check_id expected to be basetypes.StringValue, was: %T`, dataQualityCheckIdAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DataQualityChecksValue{
		DataQualityCheckId: dataQualityCheckIdVal,
		Name:               nameVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewDataQualityChecksValueNull() DataQualityChecksValue {
	return DataQualityChecksValue{
		state: attr.ValueStateNull,
	}
}

func NewDataQualityChecksValueUnknown() DataQualityChecksValue {
	return DataQualityChecksValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDataQualityChecksValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DataQualityChecksValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DataQualityChecksValue Attribute Value",
				"While creating a DataQualityChecksValue value, a missing attribute value was detected. "+
					"A DataQualityChecksValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataQualityChecksValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DataQualityChecksValue Attribute Type",
				"While creating a DataQualityChecksValue value, an invalid attribute value was detected. "+
					"A DataQualityChecksValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataQualityChecksValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DataQualityChecksValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DataQualityChecksValue Attribute Value",
				"While creating a DataQualityChecksValue value, an extra attribute value was detected. "+
					"A DataQualityChecksValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DataQualityChecksValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDataQualityChecksValueUnknown(), diags
	}

	dataQualityCheckIdAttribute, ok := attributes["data_quality_check_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`data_quality_check_id is missing from object`)

		return NewDataQualityChecksValueUnknown(), diags
	}

	dataQualityCheckIdVal, ok := dataQualityCheckIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`data_quality_check_id expected to be basetypes.StringValue, was: %T`, dataQualityCheckIdAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewDataQualityChecksValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return NewDataQualityChecksValueUnknown(), diags
	}

	return DataQualityChecksValue{
		DataQualityCheckId: dataQualityCheckIdVal,
		Name:               nameVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewDataQualityChecksValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DataQualityChecksValue {
	object, diags := NewDataQualityChecksValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDataQualityChecksValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DataQualityChecksType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDataQualityChecksValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDataQualityChecksValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDataQualityChecksValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDataQualityChecksValueMust(DataQualityChecksValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DataQualityChecksType) ValueType(ctx context.Context) attr.Value {
	return DataQualityChecksValue{}
}

var _ basetypes.ObjectValuable = DataQualityChecksValue{}

type DataQualityChecksValue struct {
	DataQualityCheckId basetypes.StringValue `tfsdk:"data_quality_check_id"`
	Name               basetypes.StringValue `tfsdk:"name"`
	state              attr.ValueState
}

func (v DataQualityChecksValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["data_quality_check_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.DataQualityCheckId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["data_quality_check_id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DataQualityChecksValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DataQualityChecksValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DataQualityChecksValue) String() string {
	return "DataQualityChecksValue"
}

func (v DataQualityChecksValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"data_quality_check_id": basetypes.StringType{},
		"name":                  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"data_quality_check_id": v.DataQualityCheckId,
			"name":                  v.Name,
		})

	return objVal, diags
}

func (v DataQualityChecksValue) Equal(o attr.Value) bool {
	other, ok := o.(DataQualityChecksValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.DataQualityCheckId.Equal(other.DataQualityCheckId) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v DataQualityChecksValue) Type(ctx context.Context) attr.Type {
	return DataQualityChecksType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DataQualityChecksValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"data_quality_check_id": basetypes.StringType{},
		"name":                  basetypes.StringType{},
	}
}
