// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_data_product

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func DataProductResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"catalog": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"catalog_id": schema.StringAttribute{
						Computed:            true,
						Description:         "Catalog Id (read only)",
						MarkdownDescription: "Catalog Id (read only)",
					},
					"catalog_kind": schema.StringAttribute{
						Computed:            true,
						Description:         "Kind of catalog (read only)",
						MarkdownDescription: "Kind of catalog (read only)",
					},
					"catalog_name": schema.StringAttribute{
						Computed:            true,
						Description:         "Name of the catalog (read only)",
						MarkdownDescription: "Name of the catalog (read only)",
					},
					"local_regions": schema.ListAttribute{
						ElementType:         types.StringType,
						Computed:            true,
						Description:         "Set of local regions for the catalog (read only)",
						MarkdownDescription: "Set of local regions for the catalog (read only)",
					},
				},
				CustomType: CatalogType{
					ObjectType: types.ObjectType{
						AttrTypes: CatalogValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Catalog details (read only)",
				MarkdownDescription: "Catalog details (read only)",
			},
			"catalog_id": schema.StringAttribute{
				Required:            true,
				Description:         "Catalog ID",
				MarkdownDescription: "Catalog ID",
			},
			"contacts": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"email": schema.StringAttribute{
							Required:            true,
							Description:         "User email (read only)",
							MarkdownDescription: "User email (read only)",
						},
						"user_id": schema.StringAttribute{
							Required:            true,
							Description:         "User ID (read only)",
							MarkdownDescription: "User ID (read only)",
						},
					},
					CustomType: ContactsType{
						ObjectType: types.ObjectType{
							AttrTypes: ContactsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Required:            true,
				Description:         "Data Product contacts (read only)",
				MarkdownDescription: "Data Product contacts (read only)",
			},
			"created_by": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"email": schema.StringAttribute{
						Computed:            true,
						Description:         "User email (read only)",
						MarkdownDescription: "User email (read only)",
					},
					"user_id": schema.StringAttribute{
						Computed:            true,
						Description:         "User ID (read only)",
						MarkdownDescription: "User ID (read only)",
					},
				},
				CustomType: CreatedByType{
					ObjectType: types.ObjectType{
						AttrTypes: CreatedByValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Created by user. If empty then the user is inactive/deleted. (read only)",
				MarkdownDescription: "Created by user. If empty then the user is inactive/deleted. (read only)",
			},
			"created_on": schema.StringAttribute{
				Computed:            true,
				Description:         "Creation date (read only)",
				MarkdownDescription: "Creation date (read only)",
			},
			"data_product_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Data Product ID (read only)",
				MarkdownDescription: "Data Product ID (read only)",
			},
			"default_cluster_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Default cluster ID for Data Product",
				MarkdownDescription: "Default cluster ID for Data Product",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Long form description of Data Product",
				MarkdownDescription: "Long form description of Data Product",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A Galaxy Data Product",
				MarkdownDescription: "A Galaxy Data Product",
			},
			"links": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							Required:            true,
							Description:         "The name of the link (read only)",
							MarkdownDescription: "The name of the link (read only)",
						},
						"uri": schema.StringAttribute{
							Required:            true,
							Description:         "The link URI (read only)",
							MarkdownDescription: "The link URI (read only)",
						},
					},
					CustomType: LinksType{
						ObjectType: types.ObjectType{
							AttrTypes: LinksValue{}.AttributeTypes(ctx),
						},
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Any links for this Data Product (read only)",
				MarkdownDescription: "Any links for this Data Product (read only)",
			},
			"modified_by": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"email": schema.StringAttribute{
						Computed:            true,
						Description:         "User email (read only)",
						MarkdownDescription: "User email (read only)",
					},
					"user_id": schema.StringAttribute{
						Computed:            true,
						Description:         "User ID (read only)",
						MarkdownDescription: "User ID (read only)",
					},
				},
				CustomType: ModifiedByType{
					ObjectType: types.ObjectType{
						AttrTypes: ModifiedByValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Created by user. If empty then the user is inactive/deleted. (read only)",
				MarkdownDescription: "Created by user. If empty then the user is inactive/deleted. (read only)",
			},
			"modified_on": schema.StringAttribute{
				Computed:            true,
				Description:         "Modified date (read only)",
				MarkdownDescription: "Modified date (read only)",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Data Product name",
				MarkdownDescription: "Data Product name",
			},
			"schema_name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the data product schema",
				MarkdownDescription: "Name of the data product schema",
			},
			"summary": schema.StringAttribute{
				Required:            true,
				Description:         "Short summary of Data Product",
				MarkdownDescription: "Short summary of Data Product",
			},
		},
	}
}

type DataProductModel struct {
	Catalog          CatalogValue    `tfsdk:"catalog"`
	CatalogId        types.String    `tfsdk:"catalog_id"`
	Contacts         types.List      `tfsdk:"contacts"`
	CreatedBy        CreatedByValue  `tfsdk:"created_by"`
	CreatedOn        types.String    `tfsdk:"created_on"`
	DataProductId    types.String    `tfsdk:"data_product_id"`
	DefaultClusterId types.String    `tfsdk:"default_cluster_id"`
	Description      types.String    `tfsdk:"description"`
	Id               types.String    `tfsdk:"id"`
	Links            types.List      `tfsdk:"links"`
	ModifiedBy       ModifiedByValue `tfsdk:"modified_by"`
	ModifiedOn       types.String    `tfsdk:"modified_on"`
	Name             types.String    `tfsdk:"name"`
	SchemaName       types.String    `tfsdk:"schema_name"`
	Summary          types.String    `tfsdk:"summary"`
}

var _ basetypes.ObjectTypable = CatalogType{}

type CatalogType struct {
	basetypes.ObjectType
}

func (t CatalogType) Equal(o attr.Type) bool {
	other, ok := o.(CatalogType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CatalogType) String() string {
	return "CatalogType"
}

func (t CatalogType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	catalogIdAttribute, ok := attributes["catalog_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`catalog_id is missing from object`)

		return nil, diags
	}

	catalogIdVal, ok := catalogIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`catalog_id expected to be basetypes.StringValue, was: %T`, catalogIdAttribute))
	}

	catalogKindAttribute, ok := attributes["catalog_kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`catalog_kind is missing from object`)

		return nil, diags
	}

	catalogKindVal, ok := catalogKindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`catalog_kind expected to be basetypes.StringValue, was: %T`, catalogKindAttribute))
	}

	catalogNameAttribute, ok := attributes["catalog_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`catalog_name is missing from object`)

		return nil, diags
	}

	catalogNameVal, ok := catalogNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`catalog_name expected to be basetypes.StringValue, was: %T`, catalogNameAttribute))
	}

	localRegionsAttribute, ok := attributes["local_regions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`local_regions is missing from object`)

		return nil, diags
	}

	localRegionsVal, ok := localRegionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`local_regions expected to be basetypes.ListValue, was: %T`, localRegionsAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CatalogValue{
		CatalogId:    catalogIdVal,
		CatalogKind:  catalogKindVal,
		CatalogName:  catalogNameVal,
		LocalRegions: localRegionsVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewCatalogValueNull() CatalogValue {
	return CatalogValue{
		state: attr.ValueStateNull,
	}
}

func NewCatalogValueUnknown() CatalogValue {
	return CatalogValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCatalogValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CatalogValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CatalogValue Attribute Value",
				"While creating a CatalogValue value, a missing attribute value was detected. "+
					"A CatalogValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CatalogValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CatalogValue Attribute Type",
				"While creating a CatalogValue value, an invalid attribute value was detected. "+
					"A CatalogValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CatalogValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CatalogValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CatalogValue Attribute Value",
				"While creating a CatalogValue value, an extra attribute value was detected. "+
					"A CatalogValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CatalogValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCatalogValueUnknown(), diags
	}

	catalogIdAttribute, ok := attributes["catalog_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`catalog_id is missing from object`)

		return NewCatalogValueUnknown(), diags
	}

	catalogIdVal, ok := catalogIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`catalog_id expected to be basetypes.StringValue, was: %T`, catalogIdAttribute))
	}

	catalogKindAttribute, ok := attributes["catalog_kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`catalog_kind is missing from object`)

		return NewCatalogValueUnknown(), diags
	}

	catalogKindVal, ok := catalogKindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`catalog_kind expected to be basetypes.StringValue, was: %T`, catalogKindAttribute))
	}

	catalogNameAttribute, ok := attributes["catalog_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`catalog_name is missing from object`)

		return NewCatalogValueUnknown(), diags
	}

	catalogNameVal, ok := catalogNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`catalog_name expected to be basetypes.StringValue, was: %T`, catalogNameAttribute))
	}

	localRegionsAttribute, ok := attributes["local_regions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`local_regions is missing from object`)

		return NewCatalogValueUnknown(), diags
	}

	localRegionsVal, ok := localRegionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`local_regions expected to be basetypes.ListValue, was: %T`, localRegionsAttribute))
	}

	if diags.HasError() {
		return NewCatalogValueUnknown(), diags
	}

	return CatalogValue{
		CatalogId:    catalogIdVal,
		CatalogKind:  catalogKindVal,
		CatalogName:  catalogNameVal,
		LocalRegions: localRegionsVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewCatalogValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CatalogValue {
	object, diags := NewCatalogValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCatalogValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CatalogType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCatalogValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCatalogValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCatalogValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCatalogValueMust(CatalogValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CatalogType) ValueType(ctx context.Context) attr.Value {
	return CatalogValue{}
}

var _ basetypes.ObjectValuable = CatalogValue{}

type CatalogValue struct {
	CatalogId    basetypes.StringValue `tfsdk:"catalog_id"`
	CatalogKind  basetypes.StringValue `tfsdk:"catalog_kind"`
	CatalogName  basetypes.StringValue `tfsdk:"catalog_name"`
	LocalRegions basetypes.ListValue   `tfsdk:"local_regions"`
	state        attr.ValueState
}

func (v CatalogValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["catalog_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["catalog_kind"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["catalog_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["local_regions"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.CatalogId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["catalog_id"] = val

		val, err = v.CatalogKind.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["catalog_kind"] = val

		val, err = v.CatalogName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["catalog_name"] = val

		val, err = v.LocalRegions.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["local_regions"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CatalogValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CatalogValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CatalogValue) String() string {
	return "CatalogValue"
}

func (v CatalogValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var localRegionsVal basetypes.ListValue
	switch {
	case v.LocalRegions.IsUnknown():
		localRegionsVal = types.ListUnknown(types.StringType)
	case v.LocalRegions.IsNull():
		localRegionsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		localRegionsVal, d = types.ListValue(types.StringType, v.LocalRegions.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"catalog_id":   basetypes.StringType{},
			"catalog_kind": basetypes.StringType{},
			"catalog_name": basetypes.StringType{},
			"local_regions": basetypes.ListType{
				ElemType: types.StringType,
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"catalog_id":   basetypes.StringType{},
		"catalog_kind": basetypes.StringType{},
		"catalog_name": basetypes.StringType{},
		"local_regions": basetypes.ListType{
			ElemType: types.StringType,
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"catalog_id":    v.CatalogId,
			"catalog_kind":  v.CatalogKind,
			"catalog_name":  v.CatalogName,
			"local_regions": localRegionsVal,
		})

	return objVal, diags
}

func (v CatalogValue) Equal(o attr.Value) bool {
	other, ok := o.(CatalogValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CatalogId.Equal(other.CatalogId) {
		return false
	}

	if !v.CatalogKind.Equal(other.CatalogKind) {
		return false
	}

	if !v.CatalogName.Equal(other.CatalogName) {
		return false
	}

	if !v.LocalRegions.Equal(other.LocalRegions) {
		return false
	}

	return true
}

func (v CatalogValue) Type(ctx context.Context) attr.Type {
	return CatalogType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CatalogValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"catalog_id":   basetypes.StringType{},
		"catalog_kind": basetypes.StringType{},
		"catalog_name": basetypes.StringType{},
		"local_regions": basetypes.ListType{
			ElemType: types.StringType,
		},
	}
}

var _ basetypes.ObjectTypable = ContactsType{}

type ContactsType struct {
	basetypes.ObjectType
}

func (t ContactsType) Equal(o attr.Type) bool {
	other, ok := o.(ContactsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ContactsType) String() string {
	return "ContactsType"
}

func (t ContactsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return nil, diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	userIdAttribute, ok := attributes["user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_id is missing from object`)

		return nil, diags
	}

	userIdVal, ok := userIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_id expected to be basetypes.StringValue, was: %T`, userIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ContactsValue{
		Email:  emailVal,
		UserId: userIdVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewContactsValueNull() ContactsValue {
	return ContactsValue{
		state: attr.ValueStateNull,
	}
}

func NewContactsValueUnknown() ContactsValue {
	return ContactsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewContactsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ContactsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ContactsValue Attribute Value",
				"While creating a ContactsValue value, a missing attribute value was detected. "+
					"A ContactsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ContactsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ContactsValue Attribute Type",
				"While creating a ContactsValue value, an invalid attribute value was detected. "+
					"A ContactsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ContactsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ContactsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ContactsValue Attribute Value",
				"While creating a ContactsValue value, an extra attribute value was detected. "+
					"A ContactsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ContactsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewContactsValueUnknown(), diags
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return NewContactsValueUnknown(), diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	userIdAttribute, ok := attributes["user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_id is missing from object`)

		return NewContactsValueUnknown(), diags
	}

	userIdVal, ok := userIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_id expected to be basetypes.StringValue, was: %T`, userIdAttribute))
	}

	if diags.HasError() {
		return NewContactsValueUnknown(), diags
	}

	return ContactsValue{
		Email:  emailVal,
		UserId: userIdVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewContactsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ContactsValue {
	object, diags := NewContactsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewContactsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ContactsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewContactsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewContactsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewContactsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewContactsValueMust(ContactsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ContactsType) ValueType(ctx context.Context) attr.Value {
	return ContactsValue{}
}

var _ basetypes.ObjectValuable = ContactsValue{}

type ContactsValue struct {
	Email  basetypes.StringValue `tfsdk:"email"`
	UserId basetypes.StringValue `tfsdk:"user_id"`
	state  attr.ValueState
}

func (v ContactsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["user_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Email.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email"] = val

		val, err = v.UserId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["user_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ContactsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ContactsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ContactsValue) String() string {
	return "ContactsValue"
}

func (v ContactsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"email":   basetypes.StringType{},
		"user_id": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"email":   v.Email,
			"user_id": v.UserId,
		})

	return objVal, diags
}

func (v ContactsValue) Equal(o attr.Value) bool {
	other, ok := o.(ContactsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Email.Equal(other.Email) {
		return false
	}

	if !v.UserId.Equal(other.UserId) {
		return false
	}

	return true
}

func (v ContactsValue) Type(ctx context.Context) attr.Type {
	return ContactsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ContactsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"email":   basetypes.StringType{},
		"user_id": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = CreatedByType{}

type CreatedByType struct {
	basetypes.ObjectType
}

func (t CreatedByType) Equal(o attr.Type) bool {
	other, ok := o.(CreatedByType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CreatedByType) String() string {
	return "CreatedByType"
}

func (t CreatedByType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return nil, diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	userIdAttribute, ok := attributes["user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_id is missing from object`)

		return nil, diags
	}

	userIdVal, ok := userIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_id expected to be basetypes.StringValue, was: %T`, userIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CreatedByValue{
		Email:  emailVal,
		UserId: userIdVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewCreatedByValueNull() CreatedByValue {
	return CreatedByValue{
		state: attr.ValueStateNull,
	}
}

func NewCreatedByValueUnknown() CreatedByValue {
	return CreatedByValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCreatedByValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CreatedByValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CreatedByValue Attribute Value",
				"While creating a CreatedByValue value, a missing attribute value was detected. "+
					"A CreatedByValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CreatedByValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CreatedByValue Attribute Type",
				"While creating a CreatedByValue value, an invalid attribute value was detected. "+
					"A CreatedByValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CreatedByValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CreatedByValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CreatedByValue Attribute Value",
				"While creating a CreatedByValue value, an extra attribute value was detected. "+
					"A CreatedByValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CreatedByValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCreatedByValueUnknown(), diags
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return NewCreatedByValueUnknown(), diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	userIdAttribute, ok := attributes["user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_id is missing from object`)

		return NewCreatedByValueUnknown(), diags
	}

	userIdVal, ok := userIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_id expected to be basetypes.StringValue, was: %T`, userIdAttribute))
	}

	if diags.HasError() {
		return NewCreatedByValueUnknown(), diags
	}

	return CreatedByValue{
		Email:  emailVal,
		UserId: userIdVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewCreatedByValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CreatedByValue {
	object, diags := NewCreatedByValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCreatedByValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CreatedByType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCreatedByValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCreatedByValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCreatedByValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCreatedByValueMust(CreatedByValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CreatedByType) ValueType(ctx context.Context) attr.Value {
	return CreatedByValue{}
}

var _ basetypes.ObjectValuable = CreatedByValue{}

type CreatedByValue struct {
	Email  basetypes.StringValue `tfsdk:"email"`
	UserId basetypes.StringValue `tfsdk:"user_id"`
	state  attr.ValueState
}

func (v CreatedByValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["user_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Email.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email"] = val

		val, err = v.UserId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["user_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CreatedByValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CreatedByValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CreatedByValue) String() string {
	return "CreatedByValue"
}

func (v CreatedByValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"email":   basetypes.StringType{},
		"user_id": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"email":   v.Email,
			"user_id": v.UserId,
		})

	return objVal, diags
}

func (v CreatedByValue) Equal(o attr.Value) bool {
	other, ok := o.(CreatedByValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Email.Equal(other.Email) {
		return false
	}

	if !v.UserId.Equal(other.UserId) {
		return false
	}

	return true
}

func (v CreatedByValue) Type(ctx context.Context) attr.Type {
	return CreatedByType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CreatedByValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"email":   basetypes.StringType{},
		"user_id": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = LinksType{}

type LinksType struct {
	basetypes.ObjectType
}

func (t LinksType) Equal(o attr.Type) bool {
	other, ok := o.(LinksType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t LinksType) String() string {
	return "LinksType"
}

func (t LinksType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return nil, diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return LinksValue{
		Name:  nameVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewLinksValueNull() LinksValue {
	return LinksValue{
		state: attr.ValueStateNull,
	}
}

func NewLinksValueUnknown() LinksValue {
	return LinksValue{
		state: attr.ValueStateUnknown,
	}
}

func NewLinksValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (LinksValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing LinksValue Attribute Value",
				"While creating a LinksValue value, a missing attribute value was detected. "+
					"A LinksValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LinksValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid LinksValue Attribute Type",
				"While creating a LinksValue value, an invalid attribute value was detected. "+
					"A LinksValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LinksValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("LinksValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra LinksValue Attribute Value",
				"While creating a LinksValue value, an extra attribute value was detected. "+
					"A LinksValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra LinksValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewLinksValueUnknown(), diags
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewLinksValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return NewLinksValueUnknown(), diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return NewLinksValueUnknown(), diags
	}

	return LinksValue{
		Name:  nameVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewLinksValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) LinksValue {
	object, diags := NewLinksValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewLinksValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t LinksType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewLinksValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewLinksValueUnknown(), nil
	}

	if in.IsNull() {
		return NewLinksValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewLinksValueMust(LinksValue{}.AttributeTypes(ctx), attributes), nil
}

func (t LinksType) ValueType(ctx context.Context) attr.Value {
	return LinksValue{}
}

var _ basetypes.ObjectValuable = LinksValue{}

type LinksValue struct {
	Name  basetypes.StringValue `tfsdk:"name"`
	Uri   basetypes.StringValue `tfsdk:"uri"`
	state attr.ValueState
}

func (v LinksValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uri"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Uri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uri"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v LinksValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v LinksValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v LinksValue) String() string {
	return "LinksValue"
}

func (v LinksValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"name": basetypes.StringType{},
		"uri":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"name": v.Name,
			"uri":  v.Uri,
		})

	return objVal, diags
}

func (v LinksValue) Equal(o attr.Value) bool {
	other, ok := o.(LinksValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Uri.Equal(other.Uri) {
		return false
	}

	return true
}

func (v LinksValue) Type(ctx context.Context) attr.Type {
	return LinksType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v LinksValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"name": basetypes.StringType{},
		"uri":  basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ModifiedByType{}

type ModifiedByType struct {
	basetypes.ObjectType
}

func (t ModifiedByType) Equal(o attr.Type) bool {
	other, ok := o.(ModifiedByType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ModifiedByType) String() string {
	return "ModifiedByType"
}

func (t ModifiedByType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return nil, diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	userIdAttribute, ok := attributes["user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_id is missing from object`)

		return nil, diags
	}

	userIdVal, ok := userIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_id expected to be basetypes.StringValue, was: %T`, userIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ModifiedByValue{
		Email:  emailVal,
		UserId: userIdVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewModifiedByValueNull() ModifiedByValue {
	return ModifiedByValue{
		state: attr.ValueStateNull,
	}
}

func NewModifiedByValueUnknown() ModifiedByValue {
	return ModifiedByValue{
		state: attr.ValueStateUnknown,
	}
}

func NewModifiedByValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ModifiedByValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ModifiedByValue Attribute Value",
				"While creating a ModifiedByValue value, a missing attribute value was detected. "+
					"A ModifiedByValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ModifiedByValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ModifiedByValue Attribute Type",
				"While creating a ModifiedByValue value, an invalid attribute value was detected. "+
					"A ModifiedByValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ModifiedByValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ModifiedByValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ModifiedByValue Attribute Value",
				"While creating a ModifiedByValue value, an extra attribute value was detected. "+
					"A ModifiedByValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ModifiedByValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewModifiedByValueUnknown(), diags
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return NewModifiedByValueUnknown(), diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	userIdAttribute, ok := attributes["user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_id is missing from object`)

		return NewModifiedByValueUnknown(), diags
	}

	userIdVal, ok := userIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_id expected to be basetypes.StringValue, was: %T`, userIdAttribute))
	}

	if diags.HasError() {
		return NewModifiedByValueUnknown(), diags
	}

	return ModifiedByValue{
		Email:  emailVal,
		UserId: userIdVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewModifiedByValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ModifiedByValue {
	object, diags := NewModifiedByValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewModifiedByValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ModifiedByType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewModifiedByValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewModifiedByValueUnknown(), nil
	}

	if in.IsNull() {
		return NewModifiedByValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewModifiedByValueMust(ModifiedByValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ModifiedByType) ValueType(ctx context.Context) attr.Value {
	return ModifiedByValue{}
}

var _ basetypes.ObjectValuable = ModifiedByValue{}

type ModifiedByValue struct {
	Email  basetypes.StringValue `tfsdk:"email"`
	UserId basetypes.StringValue `tfsdk:"user_id"`
	state  attr.ValueState
}

func (v ModifiedByValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["user_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Email.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email"] = val

		val, err = v.UserId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["user_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ModifiedByValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ModifiedByValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ModifiedByValue) String() string {
	return "ModifiedByValue"
}

func (v ModifiedByValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"email":   basetypes.StringType{},
		"user_id": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"email":   v.Email,
			"user_id": v.UserId,
		})

	return objVal, diags
}

func (v ModifiedByValue) Equal(o attr.Value) bool {
	other, ok := o.(ModifiedByValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Email.Equal(other.Email) {
		return false
	}

	if !v.UserId.Equal(other.UserId) {
		return false
	}

	return true
}

func (v ModifiedByValue) Type(ctx context.Context) attr.Type {
	return ModifiedByType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ModifiedByValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"email":   basetypes.StringType{},
		"user_id": basetypes.StringType{},
	}
}
