// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_column_mask

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ColumnMaskDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"column_mask_id": schema.StringAttribute{
				Required:            true,
				Description:         "- A column mask\n- This parameter can be looked up using `name` instead of its Id. Use `name=value` instead of an Id to lookup/search using the `value`. `value` must be encoded ([see RFC](https://www.rfc-editor.org/rfc/rfc3986#section-2.2) including `=`)\n",
				MarkdownDescription: "- A column mask\n- This parameter can be looked up using `name` instead of its Id. Use `name=value` instead of an Id to lookup/search using the `value`. `value` must be encoded ([see RFC](https://www.rfc-editor.org/rfc/rfc3986#section-2.2) including `=`)\n",
			},
			"column_mask_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Column Mask type (read only)",
				MarkdownDescription: "Column Mask type (read only)",
			},
			"created": schema.StringAttribute{
				Computed:            true,
				Description:         "Created on (read only)",
				MarkdownDescription: "Created on (read only)",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "Description (read only)",
				MarkdownDescription: "Description (read only)",
			},
			"expression": schema.StringAttribute{
				Computed:            true,
				Description:         "Column Mask expression (read only)",
				MarkdownDescription: "Column Mask expression (read only)",
			},
			"modified": schema.StringAttribute{
				Computed:            true,
				Description:         "Modified on (read only)",
				MarkdownDescription: "Modified on (read only)",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Column Mask name (read only)",
				MarkdownDescription: "Column Mask name (read only)",
			},
		},
	}
}

type ColumnMaskModel struct {
	ColumnMaskId   types.String `tfsdk:"column_mask_id"`
	ColumnMaskType types.String `tfsdk:"column_mask_type"`
	Created        types.String `tfsdk:"created"`
	Description    types.String `tfsdk:"description"`
	Expression     types.String `tfsdk:"expression"`
	Modified       types.String `tfsdk:"modified"`
	Name           types.String `tfsdk:"name"`
}
