// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_bigquery_catalog

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func BigqueryCatalogResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"catalog_id": schema.StringAttribute{
				Computed:            true,
				Description:         "BigQuery catalog identifier (read only)",
				MarkdownDescription: "BigQuery catalog identifier (read only)",
			},
			"credentials_key": schema.StringAttribute{
				Required:            true,
				Description:         "Base64 encoded or plain text BigQuery JSON key",
				MarkdownDescription: "Base64 encoded or plain text BigQuery JSON key",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Catalog description",
				MarkdownDescription: "Catalog description",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A catalog connecting to BigQuery",
				MarkdownDescription: "A catalog connecting to BigQuery",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Catalog name",
				MarkdownDescription: "Catalog name",
			},
			"parent_project_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The Google Cloud Project ID to bill for the export. Mutually required with projectId",
				MarkdownDescription: "The Google Cloud Project ID to bill for the export. Mutually required with projectId",
			},
			"project_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The Google Cloud Project ID. Mutually required with parentProjectId",
				MarkdownDescription: "The Google Cloud Project ID. Mutually required with parentProjectId",
			},
			"read_only": schema.BoolAttribute{
				Required:            true,
				Description:         "Is catalog read only",
				MarkdownDescription: "Is catalog read only",
			},
			"validate": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Validate catalog configuration before creation",
				MarkdownDescription: "Validate catalog configuration before creation",
			},
		},
	}
}

type BigqueryCatalogModel struct {
	CatalogId       types.String `tfsdk:"catalog_id"`
	CredentialsKey  types.String `tfsdk:"credentials_key"`
	Description     types.String `tfsdk:"description"`
	Id              types.String `tfsdk:"id"`
	Name            types.String `tfsdk:"name"`
	ParentProjectId types.String `tfsdk:"parent_project_id"`
	ProjectId       types.String `tfsdk:"project_id"`
	ReadOnly        types.Bool   `tfsdk:"read_only"`
	Validate        types.Bool   `tfsdk:"validate"`
}
