// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_kafka_ingest_sources

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func KafkaIngestSourcesDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"result": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"description": schema.StringAttribute{
							Computed:            true,
							Description:         "Ingest source description",
							MarkdownDescription: "Ingest source description",
						},
						"kafka_brokers": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "Kafka brokers for this source",
							MarkdownDescription: "Kafka brokers for this source",
						},
						"kafka_ingest_source_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Ingest source ID",
							MarkdownDescription: "Ingest source ID",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "Ingest source name",
							MarkdownDescription: "Ingest source name",
						},
					},
					CustomType: ResultType{
						ObjectType: types.ObjectType{
							AttrTypes: ResultValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "A page of results.",
				MarkdownDescription: "A page of results.",
			},
		},
	}
}

type KafkaIngestSourcesModel struct {
	Result types.List `tfsdk:"result"`
}

var _ basetypes.ObjectTypable = ResultType{}

type ResultType struct {
	basetypes.ObjectType
}

func (t ResultType) Equal(o attr.Type) bool {
	other, ok := o.(ResultType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ResultType) String() string {
	return "ResultType"
}

func (t ResultType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	kafkaBrokersAttribute, ok := attributes["kafka_brokers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kafka_brokers is missing from object`)

		return nil, diags
	}

	kafkaBrokersVal, ok := kafkaBrokersAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kafka_brokers expected to be basetypes.ListValue, was: %T`, kafkaBrokersAttribute))
	}

	kafkaIngestSourceIdAttribute, ok := attributes["kafka_ingest_source_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kafka_ingest_source_id is missing from object`)

		return nil, diags
	}

	kafkaIngestSourceIdVal, ok := kafkaIngestSourceIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kafka_ingest_source_id expected to be basetypes.StringValue, was: %T`, kafkaIngestSourceIdAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ResultValue{
		Description:         descriptionVal,
		KafkaBrokers:        kafkaBrokersVal,
		KafkaIngestSourceId: kafkaIngestSourceIdVal,
		Name:                nameVal,
		state:               attr.ValueStateKnown,
	}, diags
}

func NewResultValueNull() ResultValue {
	return ResultValue{
		state: attr.ValueStateNull,
	}
}

func NewResultValueUnknown() ResultValue {
	return ResultValue{
		state: attr.ValueStateUnknown,
	}
}

func NewResultValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ResultValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ResultValue Attribute Value",
				"While creating a ResultValue value, a missing attribute value was detected. "+
					"A ResultValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ResultValue Attribute Type",
				"While creating a ResultValue value, an invalid attribute value was detected. "+
					"A ResultValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ResultValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ResultValue Attribute Value",
				"While creating a ResultValue value, an extra attribute value was detected. "+
					"A ResultValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ResultValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewResultValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	kafkaBrokersAttribute, ok := attributes["kafka_brokers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kafka_brokers is missing from object`)

		return NewResultValueUnknown(), diags
	}

	kafkaBrokersVal, ok := kafkaBrokersAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kafka_brokers expected to be basetypes.ListValue, was: %T`, kafkaBrokersAttribute))
	}

	kafkaIngestSourceIdAttribute, ok := attributes["kafka_ingest_source_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kafka_ingest_source_id is missing from object`)

		return NewResultValueUnknown(), diags
	}

	kafkaIngestSourceIdVal, ok := kafkaIngestSourceIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kafka_ingest_source_id expected to be basetypes.StringValue, was: %T`, kafkaIngestSourceIdAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewResultValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return NewResultValueUnknown(), diags
	}

	return ResultValue{
		Description:         descriptionVal,
		KafkaBrokers:        kafkaBrokersVal,
		KafkaIngestSourceId: kafkaIngestSourceIdVal,
		Name:                nameVal,
		state:               attr.ValueStateKnown,
	}, diags
}

func NewResultValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ResultValue {
	object, diags := NewResultValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewResultValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ResultType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewResultValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewResultValueUnknown(), nil
	}

	if in.IsNull() {
		return NewResultValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewResultValueMust(ResultValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ResultType) ValueType(ctx context.Context) attr.Value {
	return ResultValue{}
}

var _ basetypes.ObjectValuable = ResultValue{}

type ResultValue struct {
	Description         basetypes.StringValue `tfsdk:"description"`
	KafkaBrokers        basetypes.ListValue   `tfsdk:"kafka_brokers"`
	KafkaIngestSourceId basetypes.StringValue `tfsdk:"kafka_ingest_source_id"`
	Name                basetypes.StringValue `tfsdk:"name"`
	state               attr.ValueState
}

func (v ResultValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["kafka_brokers"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["kafka_ingest_source_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.KafkaBrokers.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["kafka_brokers"] = val

		val, err = v.KafkaIngestSourceId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["kafka_ingest_source_id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ResultValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ResultValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ResultValue) String() string {
	return "ResultValue"
}

func (v ResultValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var kafkaBrokersVal basetypes.ListValue
	switch {
	case v.KafkaBrokers.IsUnknown():
		kafkaBrokersVal = types.ListUnknown(types.StringType)
	case v.KafkaBrokers.IsNull():
		kafkaBrokersVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		kafkaBrokersVal, d = types.ListValue(types.StringType, v.KafkaBrokers.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"description": basetypes.StringType{},
			"kafka_brokers": basetypes.ListType{
				ElemType: types.StringType,
			},
			"kafka_ingest_source_id": basetypes.StringType{},
			"name":                   basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"description": basetypes.StringType{},
		"kafka_brokers": basetypes.ListType{
			ElemType: types.StringType,
		},
		"kafka_ingest_source_id": basetypes.StringType{},
		"name":                   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"description":            v.Description,
			"kafka_brokers":          kafkaBrokersVal,
			"kafka_ingest_source_id": v.KafkaIngestSourceId,
			"name":                   v.Name,
		})

	return objVal, diags
}

func (v ResultValue) Equal(o attr.Value) bool {
	other, ok := o.(ResultValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.KafkaBrokers.Equal(other.KafkaBrokers) {
		return false
	}

	if !v.KafkaIngestSourceId.Equal(other.KafkaIngestSourceId) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v ResultValue) Type(ctx context.Context) attr.Type {
	return ResultType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ResultValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"description": basetypes.StringType{},
		"kafka_brokers": basetypes.ListType{
			ElemType: types.StringType,
		},
		"kafka_ingest_source_id": basetypes.StringType{},
		"name":                   basetypes.StringType{},
	}
}
