// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_data_quality_check

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func DataQualityCheckResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"catalog_id": schema.StringAttribute{
				Required:            true,
				Description:         "Catalog ID",
				MarkdownDescription: "Catalog ID",
			},
			"category": schema.StringAttribute{
				Required:            true,
				Description:         "Category of data quality check",
				MarkdownDescription: "Category of data quality check",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"Validity",
						"Completeness",
						"Consistency",
						"Accuracy",
						"None",
					),
				},
			},
			"cluster_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "ClusterId to validate expression on. Required for 'SqlQuery' kind quality checks. If missing, attempt will be made to use cluster that was already configured for the schedule.",
				MarkdownDescription: "ClusterId to validate expression on. Required for 'SqlQuery' kind quality checks. If missing, attempt will be made to use cluster that was already configured for the schedule.",
			},
			"data_quality_check_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Data Quality check ID (read only)",
				MarkdownDescription: "Data Quality check ID (read only)",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Description of what this check validates",
				MarkdownDescription: "Description of what this check validates",
			},
			"kind": schema.StringAttribute{
				Required:            true,
				Description:         "Kind of data quality check",
				MarkdownDescription: "Kind of data quality check",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"QualityExpression",
						"SqlQuery",
					),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the data quality check",
				MarkdownDescription: "Name of the data quality check",
			},
			"query": schema.StringAttribute{
				Required:            true,
				Description:         "Either expression or SQL query that implements the data quality check logic.",
				MarkdownDescription: "Either expression or SQL query that implements the data quality check logic.",
			},
			"schema_id": schema.StringAttribute{
				Required:            true,
				Description:         "Schema ID",
				MarkdownDescription: "Schema ID",
			},
			"severity": schema.StringAttribute{
				Required:            true,
				Description:         "Severity level of check failures",
				MarkdownDescription: "Severity level of check failures",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"Low",
						"Medium",
						"High",
						"Critical",
					),
				},
			},
			"table_id": schema.StringAttribute{
				Required:            true,
				Description:         "Table ID",
				MarkdownDescription: "Table ID",
			},
		},
	}
}

type DataQualityCheckModel struct {
	CatalogId          types.String `tfsdk:"catalog_id"`
	Category           types.String `tfsdk:"category"`
	ClusterId          types.String `tfsdk:"cluster_id"`
	DataQualityCheckId types.String `tfsdk:"data_quality_check_id"`
	Description        types.String `tfsdk:"description"`
	Kind               types.String `tfsdk:"kind"`
	Name               types.String `tfsdk:"name"`
	Query              types.String `tfsdk:"query"`
	SchemaId           types.String `tfsdk:"schema_id"`
	Severity           types.String `tfsdk:"severity"`
	TableId            types.String `tfsdk:"table_id"`
}
