// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_cross_account_iam_role_metadatas

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func CrossAccountIamRoleMetadatasDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"external_id": schema.StringAttribute{
				Computed:            true,
				Description:         "External id (read only)",
				MarkdownDescription: "External id (read only)",
			},
			"starburst_aws_account_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Starburst AWS account id (read only)",
				MarkdownDescription: "Starburst AWS account id (read only)",
			},
		},
	}
}

type CrossAccountIamRoleMetadatasModel struct {
	ExternalId            types.String `tfsdk:"external_id"`
	StarburstAwsAccountId types.String `tfsdk:"starburst_aws_account_id"`
}
